#! /bin/bash

# setup script that is only run once at boot time

echo "Creating the nfsroot for FAI."

. /etc/fai/fai.conf

[ -d "$FAI_CONFIGDIR/class" ] || cp -a /usr/share/doc/fai-doc/examples/simple/* $FAI_CONFIGDIR

fai-setup 2>&1 | tee /var/log/fai-setup.log

echo "Log files will be saved to /var/log/fai-setup.log"

# remove me
rm $0
