#! /bin/bash

# setup script that is only run once at boot time
# set up an FAI install server

set -o pipefail

echo ""  >/dev/console
echo "Setting up the FAI install server" >/dev/console
echo ""  >/dev/console
sleep 2

. /etc/fai/fai.conf
. /etc/fai/nfsroot.conf

# copy the simple examples
if [ ! -d "$FAI_CONFIGDIR/class" ]; then
    mkdir -p $FAI_CONFIGDIR
    cp -a /usr/share/doc/fai-doc/examples/simple/* $FAI_CONFIGDIR
    ainsl /srv/fai/config/class/FAIBASE.var "LOGUSER=fai"
fi
ainsl /etc/fai/fai.conf "LOGUSER=fai"

# setup network
ifup eth0
#ip addr add 192.168.33.250/24 brd + dev eth0 # (fixed address of faiserver)
[ -x /etc/init.d/nscd ] && /etc/init.d/nscd restart

# make index, then import
apt-get update
wget 'http://192.168.33.250:3142/acng-report.html?doImport=Start+Import&calcSize=cs&asNeeded=an#bottom'

fai-setup -B /var/tmp/base.tar.xz -v 2>&1
[ $? -eq 0 ] && rm /var/tmp/base.tar.xz

# create default pxelinux boot configuration
fai-chboot -o default

# create a template for booting the installation
fai-chboot -IFv -u nfs://faiserver/srv/fai/config jessie.tmpl

# Since we do not know the MAC address, our DHCP cannot provide the hostname.
# Therefore we do explicitly set the hostname
fai-chboot -IFv -u nfs://faiserver/srv/fai/config -k hostname=xfcehost xfcehost
fai-chboot -IFv -u nfs://faiserver/srv/fai/config -k hostname=demohost demohost
for c in {01..10}; do
    fai-chboot -IFv -u nfs://faiserver/srv/fai/config -k hostname=client$c client$c
done


# move me away
mv $0 /var/tmp
exit 0
