.\"                                      Hey, EMACS: -*- nroff -*-
.TH fai-monitor-gui 1 "2011" "FAI 4"

.SH NAME
fai-monitor-gui \- fai monitor daemon, graphical interface
.SH SYNOPSIS
.B fai-monitor-gui FILE
.SH DESCRIPTION
.B fai-monitor-gui
Read fai-monitor(8) messages from FILE and create a graphical table using
PerlTk. Normally you call it this way:
.P
fai-monitor | fai-monitor-gui -
.SH OPTIONS
.TP
.B "-s "
Use smaller icons to get more machines listed inside a window.
.SH SEE ALSO
.TP
\fIfai-monitor\fP(8)
.P
.br
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use fai-monitor.  The FAI homepage is https://fai-project.org.
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
