.\"                                      Hey, EMACS: -*- nroff -*-
.if \n(zZ=1 .ig zZ
.if \n(zY=1 .ig zY
.TH fai-cd 8 "Nov 2015" "FAI 5"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.de }1
.ds ]X \&\\*(]B\\
.nr )E 0
.if !"\\$1"" .nr )I \\$1n
.}f
.ll \\n(LLu
.in \\n()Ru+\\n(INu+\\n()Iu
.ti \\n(INu
.ie !\\n()Iu+\\n()Ru-\w\\*(]Xu-3p \{\\*(]X
.br\}
.el \\*(]X\h|\\n()Iu+\\n()Ru\c
.}f
..
.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.SH NAME
fai-cd \- make a bootable CD-ROM or USB stick that performs an FAI
.SH SYNOPSIS
.B fai-cd
[\fIOPTION\fR] \-m MIRROR \fIISOFILE\fR
.br
.B fai-cd
[\fIOPTION\fR] \-B \fIFILE\fR
.br
.B fai-cd
[\fIOPTION\fR] \-d \fIURL\fR
.br
.B fai-cd
[\fIOPTION\fR] \-S \fIIMAGEFILE\fR
.br
.SH DESCRIPTION
This command creates a bootable ISO CD-ROM image that performs the
fully automatic installation from CD-ROM without an install server. The
ISO image will be written to FILE. To create the image, the
command needs the NFSROOT, the configuration space and a partial
mirror, which is created by fai-mirror. The ISO image will contain a compressed
squashfs filesystem. This hybrid CD image can also
be written to an USB stick using dd(1).

.SH OPTIONS
.TP
.BI \-A
Create a boot only CD image (also usable for an USB stick) with
autodiscover function. The CD will scan the subnet for a FAI
server. By default it shows a menu with all profiles available from
which you can select a type of installation. This image only needs 25MB.
You can add the -J option to make the image smaller.
.TP
.BI \-B
Create a boot only ISO image which does a network installation. It does not include the nfsroot, the
partitial mirror and the config space; however for it to automatically
initiate the installation -d has to be set. By default CONFIG_SRC will
be empty.
.TP
.BI \-b
After creating the ISO image burn it by calling wodim(1) (a version of
cdrecord).
.TP
.BI "\-C " CFDIR
Use CFDIR as the configuration directory. Default is /etc/fai. You can
also set the environment variable FAI_ETC_DIR.
.TP
.BI "\-d " URL
Set the location of the config space to URL (this sets
FAI_CONFIG_SRC). Set it to "" to create an ISO image without a config space. If not set, the
value of FAI_CONFIGDIR will be used. Currently no file: is allowed
here, instead set FAI_CONFIGDIR in fai.conf(5).
.TP
.BI \-e
Exclude the directory /var/tmp from the nfsroot. You may put the
file base.tar.xz in the configuration space into the subdirectory
basefiles. This option will save about 50MB of disk space. This option
will exclude the directory even when \-H is given.
.TP
.BI \-f
Force removal of an existing ISO image before creating a new one.
.TP
.BI "\-g " FILE
Use FILE as grub grub.cfg file. The script will look for FILE
in CFDIR. If FILE is located in another directory then a full path
must be specified. If not specified, use /etc/fai/grub.cfg.
.TP
.BI \-h
Show simple help and version.
.TP
.BI \-H
Do not hide directories. Using this option will consume about 45MB more
disk space on your media. By default, some directories like man pages
and locales are hidden and will not be put onto the CD or the USB stick.
.TP
.BI \-J
Use xz compression when calling mksquashfs. Default is gzip.
.TP
.BI "\-M "
Do not add the package mirror to the CD.
.TP
.BI "\-m " DIRECTORY
Use DIRECTORY as partial FAI mirror. This option is mandatory, unless
you use -M or -B.
.TP
.BI \-S
Create a squashfs image file, instead of a complete iso. This image
file can be used to fetch the nfsroot through various ways over the network.
.SH EXAMPLES
.br
After you've created a mirror with fai-mirror in /media/mirror, you
can create a CD using:

   # fai-cd \-m /media/mirror fai-cd.iso

If you want to create a bootable USB stick (here /dev/sdf) , write the
CD image to the stick via dd(1).

   # dd if=fai-cd.iso of=/dev/sdf bs=1M

It is possible to install over the network without using NFS, i.e. by
getting the nfsroot via an http request. To do so you have to create a
squashfs image using the following command:

   # fai-cd \-S squashfs.img

In addition to that you can create said image without a config space
and without a mirror. This is useful for when you want to avoid
creating a new image after modifying your config space or
updating your mirror:

   # fai-cd \-d "" \-SMeJ squashfs.img

To fetch the image via http, use the following kernel command line
option:

   root=live:http://your_server_or_IP/path/to/squashfs.img

Create the autodiscover boot image:

   # fai-cd \-JAg /etc/fai/grub.cfg.autodiscover fai-autod.iso

.SH NOTES
Additional kernel command line options can be found in the man page of
dracut.cmdline(7). fai-cd needs enough disk space in TMPDIR (/tmp by
default) for creating the compressed filesystem. You may want to set
it to another directories, before calling fai-cd.

.SH SEE ALSO
.br

.BR fai\-mirror(1)

.BR mksquashfs(1)
.SH FILES
.PD 0
.TP
.FN /etc/fai/fai.conf
The FAI configuration file.
.TP
.FN /etc/fai/grub.cfg
The default grub2 menu configuration file for fai-cd.
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
