.\"                                      Hey, EMACS: -*- nroff -*-
.TH fai-statoverride 8 "3 Sep 2008" "FAI 3.2"

.SH NAME
fai-statoverride \- dpkg-statoverride for multiple files
.SH SYNOPSIS
.B fai-statoverride FILE ...
.SH DESCRIPTION
Override owner and mode of a file or directory. Calls
dpkg-statoverride with multiple files. This command is
idempotent.
.SH SEE ALSO
.TP
\fIdpkg-statoverride\fP(8)
.P
.br
This program is part of FAI (Fully Automatic Installation).
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
