.\"                                      Hey, EMACS: -*- nroff -*-
.TH fai-diskimage 8 "August 2016" "FAI 5"

.SH NAME
fai-diskimage \- create a disk image for booting a VM
.SH SYNOPSIS
.B fai-diskimage \fIimagename\fR
.SH DESCRIPTION
.B fai-diskimage
creates imagename.raw and runs the Fully Automatic Installation on it
using the list of FAI classes. In the end you have a bootable disk
image that can be used with Qemu/KVM, VirtualBox, VMware, Xen or by your cloud infrastructure.
.SH OPTIONS
.TP
.B -C, --convert
Convert raw image to qcow2
.TP
.B \-c, --class \fICLASS\fR[,\fICLASS\fR]
Define list of FAI classes
.TP
.B -h, --help
Print help
.TP
.B -S, --size \fISIZE\fR
Set size of raw image (suffixes k M G T are supported)
.TP
.B -s, \--cspace \fIURI\fR
Location of the config space. If location starts with /, add prefix
file://. See fai.conf(5) for all supported protocols
.TP
.B -u, --hostname \fIname\fR
Set hostname to name
.TP
.B -v, --verbose
Be verbose

.SH EXAMPLES

fai-diskimage -u cloud3 -S 2G -cDEBIAN,AMD64,FAIBASE,GRUB_PC,CLOUD disk

Creates the file disk.raw.
.SH SEE ALSO
.br
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use fai-monitor.  The FAI homepage is http://fai-project.org.
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
