.\"                                      Hey, EMACS: -*- nroff -*-
.TH fai-start-stop-damon 8 "july 2003" "FAI 2.5"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
fai-start-stop-damon \- a fake of the start-stop-daemon command
.SH SYNOPSIS
.B fai-start-stop-damon
.SH DESCRIPTION

This commands returns the same exit code as start-stop-daemon(8), but
does not start any daemons.

.SH SEE ALSO
.br
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use ftar.  The FAI homepage is http://www.informatik.uni-koeln.de/fai.
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
