.\"                                      Hey, EMACS: -*- nroff -*-
.TH fai-mk-configspace 1 "2018" "FAI 5"

.SH NAME
fai-mk-configspace \- set up the FAI config space
.SH SYNOPSIS
.B fai-mk-configspace
.SH DESCRIPTION
.B fai-mk-configspace
Create the directory defined in $FAI_CONFIGDIR and
copy the examples for the FAI config space into it.
.P
.SH OPTIONS
.TP
.B "-h "
Print short help.
.P
.br
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use fai-monitor.  The FAI homepage is https://fai-project.org.
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
