.\"                                      Hey, EMACS: -*- nroff -*-
.TH fai-chboot 8 "27 may 2003" "FAI 2.4.2"
.SH NAME
fai-chboot \- manage the network boot configuration files
.SH SYNOPSIS
.B fai-chboot
[OPTION]... KERNELNAME ROOTFS HOST...
.br
.B fai-chboot
-l
.br
.B fai-chboot
-r HOST...
.br
.B fai-chboot
-i [OPTION]... HOST...
.SH DESCRIPTION
This command creates the configuration files for network booting.

KERNELNAME is the file name of the kernel that will be booted. This
kernel will mount the root filesystem from device ROOTFS. You can add
additional kernel parameters and define some FAI specific flags. For
each host one configuration file is created. The file name of the
configuration file is its IP address in upper case hexadecimal. HOST
can be a host name or an IP address.

.SH OPTIONS
.TP
.BI "\-d " DIR
Set the default directory for the network boot configuration to
DIR. The default value is /boot/fai/pxelinux.cfg/.
.TP
.BI "\-f " fai_flags
Set FAI_FLAGS. The flags must be comma separated.
.TP
.BI \-F
Set default values for FAI_FLAGS. This is the same as -f
verbose,sshd,createvt,syslogd
.TP
.B \-h
Show simle help and version.
.TP
.B \-i
Set parameters for booting the FAI install kernel. Same as -k ip=dhcp vmlinuz-install /dev/nfs
.TP
.BI "\-k " parameters
Set kernel append parameters.
.TP
.B \-l
List the configuration for all hosts.
.TP
.B \-n
Do not create configuration but show what will be done. This also
enables the verbose flag.
.TP
.B \-p
Preserve existing config files. The default is to overwrite an
existing config file.
.TP
.B \-r
Disable network booting for HOST. This renames the config file and add
the suffix .disable to it.
.TP
.B \-v
Create verbose output.
.SH EXAMPLES
.TP
fai-chboot -l
List the configuration for all hosts.
.TP
fai-chboot -iFv atom02 atom03 dom kueppers
The hosts atom02, atom03, dom and kueppers will boot the FAI install kernel.
.TP
fai-chboot -v atom-localboot /dev/hda1 atom03 
Next time atom03 will boot the kernel atom-localboot which mounts the
root filesystem from /deb/hda1.
.TP
fai-chboot memtest86.bin koeln atom02
The host atom02 will boot the memory test. Since memtest does not need
a root filesystem, you can use any string for it.

.SH NOTES
Currently only PXE boot is supported. BOOTP configuration can be
managed using the tlink utility.

.SH SEE ALSO
.br
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use fcopy.  The FAI homepage is http://www.informatik.uni-koeln.de/fai.

.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
