.\"                                      Hey, EMACS: -*- nroff -*-
.TH fai-diskimage 8 "September 2016" "FAI 5.2"

.SH NAME
fai-diskimage \- create a disk image for booting a VM
.SH SYNOPSIS
.B fai-diskimage \fIimagename\fR
.SH DESCRIPTION
.B fai-diskimage
creates a disk image that can be used with Qemu/KVM, VirtualBox,
VMware, Xen or by your cloud infrastructure. It runs runs the Fully
Automatic Installation using a list of FAI classes. In the end you
have a bootable disk image.
.SH OPTIONS
.TP
.B \-c, --class \fICLASS\fR[,\fICLASS\fR]
Define list of FAI classes
.TP
.B -h, --help
Print help
.TP
.B -S, --size \fISIZE\fR
Set size of raw image (suffixes k M G T are supported)
.TP
.B -s, \--cspace \fIURI\fR
Location of the confi	g space. If location starts with /, the prefix
file:// will be added. See fai.conf(5) for all supported protocols
.TP
.B -u, --hostname \fIname\fR
Set hostname to name
.TP
.B -v, --verbose
Be verbose

.SH EXAMPLES

 fai-diskimage -u cloud3 -S2G -cDEBIAN,AMD64,FAIBASE,GRUB_PC,CLOUD disk.raw

Creates a Debian system with a small set of software packages without
graphical desktop. The disk image disk.raw will be of size 2 GB and
the host ist called cloud3.


 cl=DEFAULT,DHCPC,DEBIAN,AMD64,FAIBASE,DEMO,GRUB_PC,UBUNTU,XENIAL,XENIAL64,XORG
 fai-diskimage -v -u cloudhost -S5G -c$cl ubuntu.qcow2

Creates a disk image of size 5GB called ubuntu.qcow2 for a Ubuntu 16.04 desktop.

.SH SEE ALSO
.br
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use fai-monitor.  The FAI homepage is http://fai-project.org.
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
