.\"                                      Hey, EMACS: -*- nroff -*-
.if \n(zZ=1 .ig zZ
.if \n(zY=1 .ig zY
.TH fai-cd 8 "5 august 2007" "FAI 3.2"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.de }1
.ds ]X \&\\*(]B\\
.nr )E 0
.if !"\\$1"" .nr )I \\$1n
.}f
.ll \\n(LLu
.in \\n()Ru+\\n(INu+\\n()Iu
.ti \\n(INu
.ie !\\n()Iu+\\n()Ru-\w\\*(]Xu-3p \{\\*(]X
.br\}
.el \\*(]X\h|\\n()Iu+\\n()Ru\c
.}f
..
.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.SH NAME
fai-cd \- make a bootable CD-ROM that performs the FAI
.SH SYNOPSIS
.B fai-cd
.RI [OPTION]...\ -m\ DIRECTORY\ FILENAME
.br
.SH DESCRIPTION
This command creates a bootable ISO CD-ROM image that performs the
fully automatic installation from CD-ROM without a install server. The
ISO image will be written to FILENAME. To create the image, the
command needs the NFSROOT, the configuration space and a partitial
mirror, which is created by fai-mirror.
.SH OPTIONS
.TP
.BI \-b
After creating the ISO image burn it by calling cdrecord(1).
.TP
.BI \-f
Force removal of an existin ISO image before creating a new one.
.TP
.BI "\-g " FILE
Use FILE as grub menu.lst file. If not specified, use /etc/fai/menu.lst.
.TP
.BI \-h
Show simle help and version.
.TP
.BI \-k
Keep the temporary filesystem for debugging. The script will sleep for
a long time, before continuing the cleanup of temp files and
mounts. Beware of killing or suspending the script itself, since a lot
of mounts will remain. This is for debugging only!
.TP
.BI "\-m " DIRECTORY
Use DIRECTORY as partitial FAI mirror. This option is mandatory.
.TP
.BI \-n
No ISO image. Do not call mkisofs to create the ISO image. This is for
creating the filesystem only. Useful for writing it to USB stick.
.TP
.BI "\-u " DIRECTORY
Copy all FAI-CD data to DIRECTORY and try to install grub onto its
device. Do not create an ISO image. This can be used to create a
bootable USB stick.
.SH SEE ALSO
.br
This program is part of FAI (Fully Automatic Installation).
The FAI homepage is http://www.informatik.uni-koeln.de/fai. 
.TP
\fBfai-mirror\fP(1)
.PD
.SH FILES
.PD 0
.TP
.FN /etc/fai/fai.conf
The FAI configuration file.
.TP
.FN /etc/fai/menu.lst
The default grub menu configuration file for fai-cd.
.TP
.FN /srv/fai/config/package_config/
The FAI package configuration directory. This directory is defined by
the variable FAI_CONFIGDIR.
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
