.\"                                      Hey, EMACS: -*- nroff -*-
.if \n(zZ=1 .ig zZ
.if \n(zY=1 .ig zY
.TH fai-make-nfsroot 8 "April 2015" "FAI 5"
.de }1
.ds ]X \&\\*(]B\\
.nr )E 0
.if !"\\$1"" .nr )I \\$1n
.}f
.ll \\n(LLu
.in \\n()Ru+\\n(INu+\\n()Iu
.ti \\n(INu
.ie !\\n()Iu+\\n()Ru-\w\\*(]Xu-3p \{\\*(]X
.br\}
.el \\*(]X\h|\\n()Iu+\\n()Ru\c
.}f
..
.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.SH NAME
fai-make-nfsroot \- create the FAI nfsroot directory
.SH SYNOPSIS
.B fai-make-nfsroot
.RI [ options ]
.SH DESCRIPTION
Create the FAI nfsroot directory as pointed by $NFSROOT in the
config_file.  This directory is necessary for the installation of
Debian on remote clients using the FAI package. The config_file
location is discussed in the OPTIONS below.

The exit code returned is 0 if all commands to build the root directory exited
successfully and >0 if an error occurs.
.SH OPTIONS
.TP
.B \-a
Adjust a generic nfsroot. Add resolv.conf, add host entries, set the root password.
.TP
.B \-B BASETGZ
Use specified BASETGZ file as base.tgz (or base.tar.gz, base.tar.xz, base.txz)
for the nfsroot. This avoids
calling debootstrap and therefore reduces the buildtime for the nfsroot.
.TP
.B \-C CFDIR
Use CFDIR as configuration directory. Default is /etc/fai. You can
also set the environment variable FAI_ETC_DIR.
.TP
.B \-f
Force overwriting an existing nfsroot. By default fai-make-nfsroot aborts
if the configuration variable NFSROOT points to a directory which already
exists. To force overwriting (and therefore rebuilding) the existing nfsroot
use this option. This option is supported starting with FAI 4.0.
Note: To update and therefore preserve an existing nfsroot see option \-k.
.TP
.B \-g
Create a generic nfsroot. Remove most install server specific data from
nfsroot. See also -a.
.TP
.B \-K
Remove all kernels from NFSROOT. This is the same as calling aptitude
purge ~nlinux-image inside the nfsroot.
.TP
.B \-k
Install additional packages defined in /etc/fai/NFSROOT into the
nfsroot. Also copies all kernels from the nfsroot to the directory $TFTPROOT.
.TP
.B \-p
Preserve ssh configs including the keys of the root account. This will
not preserve the ssh host keys inside the nfsroot.
.TP
.B \-v
Create verbose output on stdout.
.TP
.BI \-h
Show simple help.
.TP
.B \-z
Use gzip for compressing the base.tar file. Default is to use xz.

.SH NOTES
.PD 0
If you do not use NFS, you may still use the NFSROOT
directory as a staging point for building the base installation tarball.

.PD
.SH SEE ALSO
.PD 0
\fIexports\fP(5), \fInfsd\fP(8), \fIfai-setup\fP(8)

This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use fai-make-nfsroot. The FAI homepage is
http://fai-project.org.
.SH FILES
.PD 0
.TP
.FN /etc/fai/fai.conf
The FAI configuration file.
.TP
.FN /etc/fai/nfsroot.conf
The configuration file for fai-make-nfsroot.
.PD 0
.TP
.FN /etc/fai/nfsroot-hooks/
Directory containing shell scripts to be sourced at the end of fai-make-nfsroot for additional configuration of the nfsroot. Can be changed with NFSROOT_HOOKS.
.PD 0
.TP
.FN /etc/fai/apt/sources.list
Copy this file to the NFSROOT.
.PD 0
.TP
.FN /etc/fai/apt/keys/*.asc
Repository keys in .asc format found here will be installed into the NFSROOT.
.PD 0
.TP
.FN /var/log/fai/variables
The script will write the values of FAI_VERSION and NFSROOT to this file.

.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
