.\"                                      Hey, EMACS: -*- nroff -*-
.TH fai-do-scripts 1 "5 apr 2005" "FAI 2.8"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
fai-do-scripts \- call configuration scripts
.SH SYNOPSIS
.B fai-do-scripts
.RI [OPTION] " DIRECTORY"
.SH DESCRIPTION

fai-do-scripts executes all scripts in DIRECTORY which are also a
defined class. If the name of the class is a directory, all scripts
that match `[0-9][0-9]*' in this directory are executed.  So it is
possible to have several scripts of different types (shell,
cfengine,...)  to be executed for one class. For backwards compatibility,
scripts matching `S[0-9]*' are also executed, but a warning is
printed. This will be removed in a future version.

.SH OPTIONS
.TP
.B \-h
Show help, version and summary of options.
.TP
.B \-L DIR
Write log files to DIR.
.TP
.B \-n
Show type of scripts that would be executed, but do not execute them.

.SH EXAMPLES
.br
In FAI, fai-do-scripts is used in the following way: 

   # fai-do-scripts /fai/scripts

.SH SEE ALSO
.br
This program is part of FAI (Fully Automatic Installation). The FAI
homepage is http://www.informatik.uni-koeln.de/fai.

.SH AUTHOR
Written by Thomas Lange <lange@informatik.uni-koeln.de>
