.\"                                      Hey, EMACS: -*- nroff -*-
.if \n(zZ=1 .ig zZ
.if \n(zY=1 .ig zY
.TH fai-setup 8 "December 22,2001" "FAI 2.2.4"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.de }1
.ds ]X \&\\*(]B\\
.nr )E 0
.if !"\\$1"" .nr )I \\$1n
.}f
.ll \\n(LLu
.in \\n()Ru+\\n(INu+\\n()Iu
.ti \\n(INu
.ie !\\n()Iu+\\n()Ru-\w\\*(]Xu-3p \{\\*(]X
.br\}
.el \\*(]X\h|\\n()Iu+\\n()Ru\c
.}f
..
.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.SH NAME
fai-setup \- Setup script for Fully Automatic Installation (FAI)
.SH SYNOPSIS
.B fai-setup
.SH DESCRIPTION
Fully Automatic Installation (FAI) is used to provide unattended installation of
Debian GNU/Linux operating systems with a very flexible class-based system.
fai-setup is a shell script written for FAI to create the initial NFSROOT
directory, add that directory to the NFS exports configuration file
(/etc/exports), prepare the files necessary to create the network boot floppy
disk, and create the initial fai user, used for copying over the installation
logs to a centralized directory on the server.  make-fai-nfsroot(8) is called
to create the initial NFS root directory.

fai-setup should be called after each change to /etc/fai/fai.conf.
.PD
.SH SEE ALSO
.PD 0
The programs is part of FAI (fully automatic installation). See the FAI manual
for more information how to use fai-setup. The FAI homepage is
http://www.informatik.uni-koeln.de/fai.
.TP
\fImake-fai-nfsroot\fP(8), \fIexports\fP(5)
.PD
.SH FILES
.PD 0
.TP
.FN /etc/fai/fai.conf
The FAI configuration file.
.TP
.FN /etc/exports
The NFS configuration file for exported filesystems.

.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
.\" This manpage was written by Chad Walstrom <chad@debian.or>.
.\" Take my name out of this if this manpage makes it to the cvs tree.
