.\"                                      Hey, EMACS: -*- nroff -*-
.TH faimond 8 "15 Sep 2007" "FAI 3.2"

.SH NAME
faimond \- fai monitor daemon, graphical interface
.SH SYNOPSIS
.B faimond-gui FILE
.SH DESCRIPTION
.B faimond-gui
Read faimond(8) messages from FILE and create a graphical table using
PerlTk. Normally you call it this way:
.P
faimond | faimond-gui -
.SH SEE ALSO
.TP
\fIfaimond\fP(8)
.P
.br
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use faimond.  The FAI homepage is http://www.informatik.uni-koeln.de/fai.
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
