.\"                                      Hey, EMACS: -*- nroff -*-
.TH faimond 8 "10 Jun 2007" "FAI 3.2"

.SH NAME
faimond \- fai monitor daemon
.SH SYNOPSIS
.B faimond
.SH DESCRIPTION
.B faimond
receives messages from all install clients on port 4711 and prints
them to stdout.
.SH OPTIONS
.TP
.B "-p " port
Define port to listen to. Default is port 4711.
.TP
.B "-b "
Call fai-chboot for the install client if it task install was finished
properly. Default is not to call fai-chboot.
.TP
.B "-i"
Use IP address of connecting host when calling fai-chboot. This can only be used
if the hosts has the same IP when installning as when running.
.TP
.B "-l FILE"
Logfile. Default is standard out in non-daemon mode and "/var/log/faimond.log"
in daemon mode.
.TP
.B "-t TIMEOUT"
Timeout for bad clients. 0 to disable.
.TP
.B "-d"
Daemon mode.
.TP
.B "-P FILE"
PID-file. Default is "/var/run/faimond.pid". Used only if starting in daemon
mode.
.TP
.B "-T"
Print timestamps in the log.
.TP
.SH NOTES
Normally, the output will be piped to a GUI interface which displays
all information.
.SH SEE ALSO
.br
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use faimond.  The FAI homepage is http://www.informatik.uni-koeln.de/fai.
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
