.\"                                      Hey, EMACS: -*- nroff -*-
.TH faimond 8 "16 Nov 2003" "FAI 2.5.2"

.SH NAME
faimond \- fai monitor daemon
.SH SYNOPSIS
.B faimond
.SH DESCRIPTION
.B faimond
receives messages from all install clients on port 4711 and prints
them to stdout.
.SH NOTES
Normally, the output will be piped to a GUI interface which displays
all information.
.SH SEE ALSO
.br
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use faimond.  The FAI homepage is http://www.informatik.uni-koeln.de/fai.
.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
