.\"                                      Hey, EMACS: -*- nroff -*-
.TH ftar 8 "15 April 2002"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
ftar \- extract tar files using classes
.SH SYNOPSIS
.B ftar
.RI [ options ] " SOURCE"
.SH DESCRIPTION
Extract an archive from SOURCE to its target directory using classes.

SOURCE is a directory which contains one or more template files for
the source archive to extract.  Depending on the list of defined
classes, one or more archives of the source directory are selected and
extracted to the target.  The base target directory is the name of the
source directory.  Template file must have suffix .tar, .tar.gz,
or .tar.bz2 depending on the type of archive.

The exit code returned by ftar is mostly 0.  For every successfully
extracted tar file, a log message is printed to standard output.
.SH OPTIONS
.TP
Options -c, -s, -t (or their analog variables) and a SOURCE are required.
.TP
.BI \-1
Use only one archive file matching a class name.
.TP
.BI "\-c " class[class]
Define classes.  Multiple classes must be space separated.  The first class
has the lowest priority.  If not specified, use the classes from
the file /tmp/FAI_CLASES.
.TP
.B \-d
Delete all files in target directory before extracting the archive(s).
.TP
.B \-D
Create debugging output.
.TP
.B \-h
Show help, version and summary of options.
.TP
.B \-r
Recursively remove files in target directory before extracting archive.
.TP
.BI "\-s " source_dir
Look for SOURCE files relative to \fIsource_dir\fR.  Use $FAI/files if
not specified.
.TP
.BI "\-t " target_dir
Extract archives relative to \fItarget_dir\fR.  Use $FAI_ROOT if not specified.
.TP
.B \-v
Be verbose.  Not yet used.


.SH EXAMPLES
.br
Suppose the source directory /files/etc/alternatives consists of the following files:

DATALESS.tar.gz ant01.tar.bz2

Each file is a compressed archive.  If only class DATALESS is defined,
the following command

   # ftar -s /files -t /tmp/target /etc/alternatives

is equal to

   # tar -C /tmp/target -zxf /files/etc/alternatives/DATALESS.tar.gz

If additionally class ant01 is defined, the following command is also executed

   # tar -C /tmp/target -jxf /files/etc/alternatives/ant01.tar.bz2

If only one archive should be extracted, the class with highest
priority is used.

.SH NOTES
Do not create a file DEFAULT if no reasonable default configuration file can be
used.  It's better to exit with an error than to extract a wrong
archive.

This command can also be used to maintain your complete directory trees on
a huge number of hosts.
.SH SEE ALSO
.br
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use ftar.  The FAI homepage is http://www.informatik.uni-koeln.de/fai.

.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
