.\"                                      Hey, EMACS: -*- nroff -*-
.if \n(zZ=1 .ig zZ
.if \n(zY=1 .ig zY
.TH make-fai-bootfloppy 8 "December 22,2001" "FAI 2.3"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.de }1
.ds ]X \&\\*(]B\\
.nr )E 0
.if !"\\$1"" .nr )I \\$1n
.}f
.ll \\n(LLu
.in \\n()Ru+\\n(INu+\\n()Iu
.ti \\n(INu
.ie !\\n()Iu+\\n()Ru-\w\\*(]Xu-3p \{\\*(]X
.br\}
.el \\*(]X\h|\\n()Iu+\\n()Ru\c
.}f
..
.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.SH NAME
make-fai-bootfloppy \- create a FAI boot floppy
.SH SYNOPSIS
.B make-fai-bootfloppy
.RI [ options ]
.SH DESCRIPTION
Create a boot floppy for the Fully Automatic Installation (FAI) package.  This
shell-script program wrapper the complexities in creating an FAI boot disk for
use with DHCP or BOOTP protocols.  It determines which protocol you would like to use for the initial kernel and places that kernel on the floppy disk with all the necessary support tools.  

The exit code returned is 0 if all commands to build the root directory exited
successfully  and !=0 if an error occurs.
.SH OPTIONS
.TP
.B "-v"
Create verbose output on stdout.
.TP
.B \-f file
Make a 1440k floppy image.
.TP
.B \-s host
Prepare a hostspecific bootfloppy by disabling DHCP and BOOTP, instead insert
network configuration into kernel command line's "ip=" statement, getting
necessary data by DNS A lookup.
.SH EXAMPLES
To make a boot floppy for my old SMC EtherCard Plus Elite 16T, I use

# make-fai-bootfloppy "reserve=0x300,32 ether=10,0x300,eth0"
.SH NOTES
.PD 0
make-fai-bootfloppy will attempt to access /dev/fd0 unless the option
-f is used. IT IS NOT DEVFSD compatible unless your devfsd
installation remaps the floppy device to the common device alias /dev/fd0.
.PD
.SH SEE ALSO
.PD 0
The programs is part of FAI (fully automatic installation). See the FAI manual
for more information how to use make-fai-bootfloppy. The FAI homepage is
http://www.informatik.uni-koeln.de/fai.
.PD
.SH FILES
.PD 0
.TP
.FN /etc/fai/fai.conf
The FAI configuration file.

.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
.\" This manpage was written by Chad Walstrom <chad@debian.or>.
.\" Take my name out of this if this manpage makes it to the cvs tree.
