.\"                                      Hey, EMACS: -*- nroff -*-
.if \n(zZ=1 .ig zZ
.if \n(zY=1 .ig zY
.TH make-fai-nfsroot 8 "December 22,2001" "FAI 2.2.4"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.de }1
.ds ]X \&\\*(]B\\
.nr )E 0
.if !"\\$1"" .nr )I \\$1n
.}f
.ll \\n(LLu
.in \\n()Ru+\\n(INu+\\n()Iu
.ti \\n(INu
.ie !\\n()Iu+\\n()Ru-\w\\*(]Xu-3p \{\\*(]X
.br\}
.el \\*(]X\h|\\n()Iu+\\n()Ru\c
.}f
..
.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.SH NAME
make-fai-nfsroot \- create the FAI nfsroot directory
.SH SYNOPSIS
.B make-fai-nfsroot
.RI [ options ]
.SH DESCRIPTION
Create the FAI nfsroot directory in /usr/lib/fai/nfsroot.  This directory is
necessary for the installation of Debian on remote clients using the FAI
package.

The exit code returned is 0 if all commands to build the root directory exited
successfully  and !=0 if an error occurs.
.SH OPTIONS
.TP
.B \-v
Create verbose output on stdout.

.SH NOTES
.PD 0
make-fai-nfsroot will attempt to add the NFSROOT directory to your /etc/exports
file for export via NFS.  If you do not use NFS, you may still use the NFSROOT
directory as a staging point for building the base installation tarball.  See
the FAI manual for more details.
.PD
.SH SEE ALSO
.PD 0
The programs is part of FAI (fully automatic installation). See the FAI manual
for more information how to use make-fai-nfsroot. The FAI homepage is
http://www.informatik.uni-koeln.de/fai.
.TP
\fImake-fai-bootfloppy\fP(8), \fIexports\fP(5), \fInfsd\fP(8)
.PD
.SH FILES
.PD 0
.TP
.FN /etc/fai/fai.conf
The FAI configuration file.

.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
.\" This manpage was written by Chad Walstrom <chad@debian.or>.
.\" Take my name out of this if this manpage makes it to the cvs tree.
