.\"                                      Hey, EMACS: -*- nroff -*-
.if \n(zZ=1 .ig zZ
.if \n(zY=1 .ig zY
.TH make-fai-bootfloppy 8 "6 feb 2003" "FAI 2.4"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.de }1
.ds ]X \&\\*(]B\\
.nr )E 0
.if !"\\$1"" .nr )I \\$1n
.}f
.ll \\n(LLu
.in \\n()Ru+\\n(INu+\\n()Iu
.ti \\n(INu
.ie !\\n()Iu+\\n()Ru-\w\\*(]Xu-3p \{\\*(]X
.br\}
.el \\*(]X\h|\\n()Iu+\\n()Ru\c
.}f
..
.\"
.\" File Name macro.  This used to be `.PN', for Path Name,
.\" but Sun doesn't seem to like that very much.
.\"
.de FN
\fI\|\\$1\|\fP
..
.SH NAME
make-fai-bootfloppy \- create a FAI boot floppy
.SH SYNOPSIS
.B make-fai-bootfloppy
[OPTIONS] [<kernel parameters>]
.SH DESCRIPTION
Creates a boot floppy for the Fully Automatic Installation (FAI)
package. This shell-script wrapper simplifies the complexities of
creating a FAI boot disk for use with DHCP or BOOTP protocols.  It
creates a bootfloppy using grub (default) or lilo as boot loader. The
installation kernel is also put onto the floppy disk which supports
DHCP, BOOTP protocol and a fixed IP address for the installation
server. All parameters are used as additional kernel parameters.

The exit code returned is 0 if all commands to build the root directory exited
successfully and >0 if an error occurs.
.SH OPTIONS


.TP
.B \-d label

use label when selection the default boot kernel (and parameters).
  d for dhcp
  b for bootp
  f for the fixed IP address for the server

Without this option both (dhcp and booth) are used.
.TP
.B \-f file
Make a 1440k floppy image.
.TP
.B \-g
Use grub as boot loader (default).
.TP
.B \-l 
Use lilo as boot loader.
.TP
.B \-m dir
Use dir as mountpoint for either floppy device or file.  Defaults to /floppy.
.TP
.B \-s host
Prepare a host specific bootfloppy by disabling DHCP and BOOTP, instead insert
network configuration into kernel command line's "ip=" statement, getting
necessary data by DNS A lookup.
.TP
.B "-v"
print verbose output

.SH EXAMPLES
Create a generic boot floppy for James ;-)

# make-fai-bootfloppy "FAI_FLAGS=sshd,createvt BOND=007"

To make the boot floppy use the DHCP protocol

# make-fai-bootfloppy "ip=dhcp"

.SH NOTES
.PD 0
make-fai-bootfloppy will attempt to access /dev/fd0 unless the option
-f is used.  IT IS NOT DEVFSD compatible unless your devfsd
installation remaps the floppy device to the common device alias /dev/fd0.
.PD
.SH SEE ALSO
.PD 0
This program is part of FAI (Fully Automatic Installation).  See the FAI manual
for more information on how to use make-fai-bootfloppy.  The FAI homepage is
http://www.informatik.uni-koeln.de/fai.
.PD
.SH FILES
.PD 0
.TP
.FN /etc/fai/fai.conf
The FAI configuration file.

.SH AUTHOR
Thomas Lange <lange@informatik.uni-koeln.de>
