.\"                                      Hey, EMACS: -*- nroff -*-
.TH nfsroot.conf 5 "January 2014" "FAI 5.0"
.\" Please adjust this date whenever revising the manpage.

.SH NAME
nfsroot.conf \- nfsroot configuration for FAI
.SH SYNOPSIS
.B /etc/fai/nfsroot.conf
.SH DESCRIPTION
The nfsroot is a file system on the install server. It is used during installation by
the install clients.
.LP
.BR nfsroot.conf
defines the essential options for the install server, which are mostly
used inside the nfsroot. Use bash(1) syntax for defining variables.

.SH VARIABLES
.TP
.B FAI_DEBOOTSTRAP
Two parameters for debootstrap(8), space separated. Debootstrap is
called as the first part of fai-make-nfsroot unless -B is used. This variable defines
SUITE and MIRROR for debootstrap. Example:

FAI_DEBOOTSTRAP="wheezy http://httpredir.debian.org/debian"

.TP
.B NFSROOT_ETC_HOSTS
This multiline variable is added to /etc/hosts inside the nfsroot.
You can use this when DNS is not available on the clients. Example:

NFSROOT_ETC_HOSTS="192.168.33.250 faiserver"

.TP
.B FAI_ROOTPW
The encrypted root password on all install
clients during the installation process. Used when log in via ssh.
This is not the password for the new installed system. Example:

FAI_ROOTPW='$1$kBnWcO.E$djxB128U7dMkrltJHPf6d1'  # pw is fai

Use mkpasswd, htpasswd or md5pass for generating the password hash.

echo "yoursecrectpassword" | mkpasswd -Hmd5 -s

.TP
.B NFSROOT
Directory on the install server where the nfsroot is created.

.TP
.B TFTPROOT
Directory on the install server for the tftp data, used by
PXE network boot.

.TP
.B FAI_CONFIGDIR
Location of the configuration space on the install server. Used by
fai-cd(8), fai-mirror(1) and fai-setup(8).

.TP
.B SSH_IDENTITY
Location of a ssh public key file. This user can log into the install
clients in as root without a password. Only useful with
FAI_FLAGS="sshd". Example:

SSH_IDENTITY=/home/admin/.ssh/id_rsa.pub

.TP
.B NFSROOT_HOOKS
Directory of hooks to be sourced at the end of fai-make-nfsroot,
i.e. they have to be shell scripts.

.TP
.B FAI_DEBOOTSTRAP_OPTS
Options that will be passed to debootstrap(8). Used for excluding
packages and for specifying a different architecture.

.SH NOTES
Normally, the nfsroot is mounted by the install kernel via NFS.  It's
also used on the FAI CD. FAI clients can also receive the nfsroot via
http. There you have to create a compressed squashfs image of the
nfsroot with fai-cd(8).

.SH SEE ALSO

.BR fai\-make-nfsroot (8),
.BR fai\-setup (8),
.BR fai (8)
.BR fai\-mirror(1)
.BR fai\-chboot(8)

.br
This file is part of FAI (Fully Automatic Installation). The FAI
homepage is http://fai-project.org.

.SH AUTHOR
This man page was written by Thomas Lange <lange@informatik.uni-koeln.de>.
