#!/usr/bin/perl

# $Id$
#*********************************************************************
#
# fai-savelog-ftp -- save log files from fai to FTP server
#
# This script is part of FAI (Fully Automatic Installation)
#
#*********************************************************************
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# A copy of the GNU General Public License is available as
# '/usr/share/common-licences/GPL' in the Debian GNU/Linux distribution
# or on the World Wide Web at http://www.gnu.org/copyleft/gpl.html. You
# can also obtain it by writing to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301, USA
#*********************************************************************

use strict;
use Net::FTP;

chomp (my $hostname = `hostname`);

print "Save log files via FTP to $ENV{LOGUSER}\@$ENV{LOGSERVER}:$hostname/$ENV{FAI_ACTION}-$ENV{fai_rundate}\n";

my $ftp = Net::FTP->new("$ENV{LOGSERVER}", Debug => 0)
   or die "Cannot connect to FTP server $ENV{LOGSERVER}.\n";
$ftp->login("$ENV{LOGUSER}", "$ENV{LOGPASSWD}")
   or die "Cannot login to FTP server $ENV{LOGSERVER} with login $ENV{LOGUSER}.\n";
$ftp->cwd("$ENV{LOGREMOTEDIR}")
   or die "Cannot change work directory to $ENV{LOGREMOTEDIR}\n";
my $ftplogdir = $ftp->mkdir("$hostname/$ENV{FAI_ACTION}-$ENV{fai_rundate}", 1) 
   or die "Cannot create dir $ENV{FAI_ACTION}-$ENV{fai_rundate}.\n";
$ftp->cwd("$ftplogdir")
   or die "Cannot change work directory to $ftplogdir.\n";

while (my $file = <$ENV{LOGDIR}/*>) {
      $ftp->put("$file");
}

$ftp->quit;
