#! /bin/sh

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin

set -e

case "$1" in
  start)
	echo -n "Updating APT: "
	apt-get update
	echo "done"
	echo $0
	rm -f $0
	;;

  *)
	N=/etc/init.d/$NAME
	echo "Usage: $N {start}" >&2
	exit 1
	;;
esac

exit 0
