#! /bin/bash

if ifclass GCE; then
    ainsl /etc/default/grub 'GRUB_TERMINAL="serial"'
    ainsl /etc/default/grub 'GRUB_SERIAL_COMMAND="serial --speed 38400 --unit=0 --word=0 --parity=no --stop=1"'
fi
