#! /bin/bash

error=0 ; trap "error=$((error|1))" ERR

$ROOTCMD grub-mkdevicemap -n -m /boot/grub/device.map
$ROOTCMD grub-mkconfig -o /boot/grub/grub.cfg
$ROOTCMD grub-install --no-floppy "(hd0)"

exit $error
