#! /bin/bash
# support for GRUB version 2 (1.98-1)

error=0 ; trap "error=$((error|1))" ERR

$ROOTCMD grub-mkdevicemap -n -m /boot/grub/device.map
$ROOTCMD grub-mkconfig -o /boot/grub/grub.cfg
GROOT=$($ROOTCMD grub-probe -tdrive -d $BOOT_DEVICE)
$ROOTCMD grub-install --no-floppy "$GROOT"
echo "Grub installed on $BOOT_DEVICE = $GROOT"

exit $error
