#! /bin/bash

# (c) Michael Goetze, 2010-11, mgoetze@mgoetze.net
# Thomas Lange, 2015

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD authconfig --enableshadow --enablemd5 \
	--enablelocauthorize --updateall
$ROOTCMD usermod -p $ROOTPW root

fcopy -v /etc/selinux/config
$ROOTCMD fixfiles onboot # this fixes the SELinux security contexts during the first boot
chmod a+rx $target

exit $error
