#! /bin/sh

# do only execute when running sunos

case `uname -s` in
     SunOS) ;;
     *) exit 0 ;;
esac

# all hosts but rubens are clients
# some have an TFT display
case $HOSTNAME in
    rubens) ;;
    dali|gaffel) ;;  # hosts which will become DATALESS 
    *) echo "SOLARIS_CLIENT" ;;
esac
case $HOSTNAME in
    reissdorf|frueh) echo "TFT RES1280" ;;
esac

# check if CD-ROM is installed
prtconf | grep cdrom >/dev/null && echo "VOLD"
prtconf | grep "usb, instance" >/dev/null && echo "USB"

# if disk is smaller than xy GB use class 4GB
# SI_DISKSIZE..... XXXXXXXXXX

if [ "$SI_NUMDISKS" -eq "1" ]; then
    [ "$SI_DISKSIZES" -le "700" ] && echo "DATALESS";
    [ "$SI_DISKSIZES" -le "1600" -a "$SI_DISKSIZES" -ge "700" ] && echo "1GB";
    [ "$SI_DISKSIZES" -ge "1600" ] && echo "4GB";
fi

# configure LPD servers
case $HOSTNAME in
    jever|malzmuehle)
	echo "LPD" ;;
esac

exit 0
