#! /bin/bash

[ -d /media/mirror ] || exit 0

echo "Copying Debian mirror from CD to local dis. This may take some time."
mkdir -p $target/var/www/debian
cp -a /media/mirror/* $target/var/www/debian

echo "deb http://faiserver/debian stable main" > $target/etc/apt/sources.list

# fix mirror, otherwise debootstrap can't work. Curently packages in sarge (fai-*)
# can not be accessed
cd $target/var/www/debian/dists
mv sarge tom
ln -s stable sarge
