#! /bin/bash

[ -d /media/mirror ] || exit 0

echo "Copying Debian mirror from CD to local dis. This may take some time."
mkdir -p $target/var/www/debian
cp -a /media/mirror/* $target/var/www/debian

echo "deb http://faiserver/debian stable main" > $target/etc/apt/sources.list

cd $target/var/www/debian/dists
ln -s stable sarge

fcopy -v /etc/rc2.d/S99fai-setup
