#! /bin/bash

set -e

. ./debian/tests/common.sh

fai-mk-configspace

# test the results of the commands called
chk-file $CS/class/50-host-classes
chk-file $CS/scripts/GRUB_EFI/10-setup
chk-file $CS/disk_config/FAIBASE
chk-file $CS/files/etc/rc.local/FAISERVER
