#! /bin/bash

set -e

. ./debian/tests/common.sh

fai-mk-configspace
# test the results of the commands called
chk-file $CS/class/50-host-classes
chk-file $CS/class/DEBIAN.var
chk-file $CS/class/40-parse-profiles.sh
chk-file $CS/scripts/GRUB_EFI/10-setup
chk-file $CS/disk_config/CLOUD
chk-file $CS/disk_config/FAIBASE
chk-file $CS/package_config/DEBIAN.gpg
chk-file $CS/package_config/DEMO
chk-file $CS/files/etc/rc.local/FAISERVER
chk-file $CS/debconf/DEBIAN
