#! /bin/bash

# fai-diskimage
# Depends fai-setup-storage
# apt -o APT::Install-Suggests=0 -o APT::Install-Recommends=0 install fai-setup-storage

set -e

. ./debian/tests/common.sh
cd "$AUTOPKGTEST_TMP"

chk-loop-device

trap "cp -vap /var/log/fai/cloud3 $AUTOPKGTEST_ARTIFACTS" INT QUIT EXIT

cl="DEBIAN,BUSTER64,AMD64,FAIBASE,GRUB_PC,DHCPC,DEMO,CLOUD,LAST"
LC_ALL=C fai-diskimage -vu cloud3 -S2G -c$cl cloud.raw


# test the results of the commands called
chk-size cloud.raw 900

mount -oloop,offset=1048576 cloud.raw /mnt
chk-size /mnt/boot 30
umount /mnt

if grep -q FAILED $ch/var/log/fai/cloud3/last/status.log; then
    error "fai-diskimage failed. See status.log"
fi

rm cloud.raw
