#! /bin/bash

# more tests for fai-cd

. ./debian/tests/common.sh
#trap "cp -vp fai-cd.log $AUTOPKGTEST_ARTIFACTS" INT QUIT EXIT

chk-loop-device

chk-file faicd64-small.iso


# more test after mounting the ISO
mount -oloop,ro faicd64-small.iso /mnt
chk-size /mnt/boot/initrd.img 40
chk-size /mnt/boot/vmlinuz 7
chk-size /mnt/LiveOS/squashfs.img 770
chk-file /mnt/boot/grub/bios.img
chk-file /mnt/FAI-CD

umount /mnt

if [ X$NO_CLEANUP != X1 ]; then
    rm faicd64-small.iso
fi
