#! /bin/bash

# more tests for fai-cd

set -e

. ./debian/tests/common.sh
trap "cp -vp fai-cd.log $AUTOPKGTEST_ARTIFACTS" INT QUIT EXIT
cd "$AUTOPKGTEST_TMP"

chk-loop-device

# more test after mounting the ISO
mount -oloop faicd64-small.iso /mnt
chk-size /mnt/boot/initrd.img 35
chk-file /mnt/FAI-CD

umount /mnt
rm faicd64-small.iso
