#! /bin/bash

set -e

. ./debian/tests/common.sh
export PATH=$PATH:/sbin
cd "$AUTOPKGTEST_TMP"

fcopy -vs $CS/files/ -t /tmp -c DEBIAN,DEMO /etc/rc.local 2>&1 && error "wrong fcopy fail"
fcopy -vs $CS/files/ -t /tmp -c FAISERVER,CLOUD /etc/rc.local
chk-file /tmp/etc/rc.local
diff $CS/files/etc/rc.local/CLOUD /tmp/etc/rc.local || error "Files are not the same."
