#! /bin/bash

# test some FAI utilities

set -e

. ./debian/tests/common.sh
cd "$AUTOPKGTEST_TMP"

echo "7565a01bd35f31ba82ab55c978c1b755  testfile"  > testfile.md5sum
ainsl -a testfile "first line"
ainsl    testfile "first line"
ainsl    testfile "second line"
ainsl    testfile "first line"
md5sum -c testfile.md5sum

fai-link linka testfile
fai-link linka testfile
fai-sed    's/testfile/newfile/' testfile.md5sum
fai-sed    's/testfile/AAA/'     testfile.md5sum
fai-sed -E 's/testfile/newfile/' testfile.md5sum
mv testfile newfile
md5sum -c testfile.md5sum

# test if symlink was created
fai-sed    's/newfile/linkb/' testfile.md5sum
fai-link linkb newfile
md5sum -c testfile.md5sum

# TODO: fcopy

rm testfile.md5sum linka linkb newfile
