#! /bin/bash

# (c) Thomas Lange, 2001-2017, lange@debian.org

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

ifclass XORG && {
    fcopy -M /etc/X11/xorg.conf
}

if ifclass UBUNTU; then
     groups="adm cdrom sudo dip plugdev lpadmin sambashare"
     $ROOTCMD addgroup --system lpadmin || true
     $ROOTCMD addgroup --system sambashare || true
fi

# add additional user account
if ! $ROOTCMD getent passwd $username ; then
    $ROOTCMD adduser --disabled-login --gecos "first user" $username
    $ROOTCMD usermod -p "$USERPW" $username
    for g in $groups; do
	$ROOTCMD adduser $username $g
    done
fi
