#! /bin/sh

# (c) Thomas Lange, 2001-2005, lange@debian.org

ifclass XFREE && {
    fcopy -M /etc/X11/XF86Config   && rm -f $target/etc/X11/XF86Config-4
    fcopy -M /etc/X11/XF86Config-4 && rm -f $target/etc/X11/XF86Config
    [ -n "$videodrv" ] || videodrv=vesa
    grep -q %%VIDEODRV%% $target/etc/X11/XF86Config-4 &&
    perl -pi.orig -pe "s/%%VIDEODRV%%/$videodrv/" $target/etc/X11/XF86Config-4
}

# add a demo user account
$ROOTCMD adduser --disabled-login --gecos "fai demo user" demo
echo "demo:$rootpw" | $ROOTCMD chpasswd --encrypted
