#! /bin/bash

# TODO: if we install from network copy the package mirror via, e.g., wget

[ -d /media/mirror ] || exit 0

echo "Copying Debian mirror from CD to local disk. This may take some time."
mkdir -p $target/var/www/debian
cp -a /media/mirror/* $target/var/www/debian

cd $target/var/www/debian/dists
# this link can only work when squeeze is released. For testing before the release use : ln -s testing squeeze
ln -s stable squeeze

fcopy -v /etc/rc2.d/S99fai-setup
