#! /bin/bash

# (c) Thomas Lange, 2006, lange@debian.org
# create entries for removable media in fstab and directories in /media

ainsl $target/etc/fstab "/dev/fd0  /media/floppy  auto  users,noauto 0 0"

cdromlist() {
    [ -f /proc/sys/dev/cdrom/info ] || return
    devs=$(grep 'drive name:' /proc/sys/dev/cdrom/info | cut -d ":" -f 2)
    for d in $devs; do
	echo $d
    done
}

fstabline () {
    line=$(printf "%-15s %-15s %-7s %-15s %-7s %s\n" "$1" "$2" "$3" "$4" "$5" "$6")
    ainsl $target/etc/fstab "$line"
}

i=0
for cdrom in $(cdromlist | tac); do
    [ $i -eq 0 ] && ln -s cdrom0 $target/media/cdrom
    [ -d $target/media/cdrom$i ] || mkdir $target/media/cdrom$i
    fstabline /dev/$cdrom /media/cdrom$i udf,iso9660 ro,user,noauto 0 0
    i=$(($i + 1))
done
