#! /bin/bash

# (c) Michael Goetze, 2010-11, mgoetze@mgoetze.net

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

$ROOTCMD authconfig --enableshadow --enablemd5 \
	--enablelocauthorize --updateall
$ROOTCMD usermod -p $ROOTPW root

fcopy -v /etc/selinux/config

exit $error
