#! /bin/bash

# (c) Stephan Adig 2011, sh@sourcecode.de

$ROOTCMD /sbin/MAKEDEV urandom
$ROOTCMD /sbin/MAKEDEV random
$ROOTCMD /sbin/MAKEDEV -m 16 hda 
$ROOTCMD /sbin/MAKEDEV sda
$ROOTCMD /sbin/MAKEDEV sdb
$ROOTCMD /sbin/MAKEDEV rtc

