#! /bin/bash

# (c) Michael Goetze, 2010-2011, mgoetze@mgoetze.net

mknod -m 600 $target/dev/hda b 3 0
mknod -m 600 $target/dev/sda b 8 0
for x in `seq 1 15`; do
    mknod -m 600 $target/dev/hda$x b 3 $x
    mknod -m 600 $target/dev/sda$x b 8 $x
done
mknod -m 600 $target/dev/rtc c 254 0
