#! /bin/bash

# (c) Michael Goetze, 2011, mgoetze@mgoetze.net

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

if [ -r $LOGDIR/disk_var.sh ] ; then
	. $LOGDIR/disk_var.sh
else
	echo "disk_var.sh not found!"
	exit 1
fi

bootdev=`device2grub $BOOT_DEVICE`
bootpart=`device2grub $BOOT_PARTITION`
version=`$ROOTCMD rpm -qv kernel | cut -d- -f2-`
if grep '[[:space:]]/boot[[:space:]]' $LOGDIR/fstab; then
	bootdir=''
else
	bootdir='/boot'
fi

$ROOTCMD grub-install --just-copy

$ROOTCMD grub --no-floppy --batch <<-EOF
	root $bootpart
	setup $bootdev
	quit
	EOF

ln -s ./menu.lst $target/boot/grub/grub.conf

if [ -f $target/boot/grub/splash.xpm.gz ]; then
	pretty="splashimage=$bootpart$bootdir/grub/splash.xpm.gz"
else
	pretty="color cyan/blue white/blue"
fi

cat > $target/boot/grub/grub.conf <<-EOF
	timeout 5
	default 0
	$pretty
	hiddenmenu
	
	title CentOS ($version)
	  root $bootpart
	  kernel $bootdir/vmlinuz-$version root=$ROOT_PARTITION ro
	  initrd $bootdir/initrd-$version.img
	EOF

echo ""
echo "Grub installed on $BOOT_DEVICE = $bootdev"
echo "Grub boot partition is $BOOT_PARTITION = $bootpart"
echo "Root partition is $ROOT_PARTITION"
echo "Boot kernel: $version"

exit $error
