#! /bin/bash

sed -i "s/PermitRootLogin yes/PermitRootLogin without-password/" $taraget/etc/ssh/sshd_config
ainsl /etc/ssh/sshd_config 'ClientAliveInterval 120'

ainsl -a /etc/modprobe.d/blacklist.conf 'blacklist pcspkr'

rm -f $target/etc/resolv.conf $target/etc/ssh/ssh_host_* $target/etc/udev/rules.d/70-persistent-net.rules $target/lib/udev/write_net_rules

# FIXME: DHCP RFC3442 is used incorrect in Azure
sed -ie 's,rfc3442-classless-static-routes,disabled-\0,' $target/etc/dhcp/dhclient.conf

