#! /bin/bash

# (c) Thomas Lange, 2001-2011, lange@debian.org
# (c) Michael Goetze, 2010-2011, mgoetze@mgoetze.net

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

ln -fs /usr/share/zoneinfo/${TIMEZONE} $target/etc/localtime

if [ -n "$IPADDR" ]; then
    ifclass DHCPC || ainsl -s $target/etc/hosts "$IPADDR $HOSTNAME.$DOMAIN $HOSTNAME"
else
    ifclass DHCPC && ainsl -s $target/etc/hosts "127.0.0.1 $HOSTNAME"
fi

fcopy -iM /etc/hosts /etc/motd

# make /root accessible only by root
chmod -c 0700 $target/root
chown -c root:root $target/root
# copy default dotfiles for root account
fcopy -ir /root

chmod -c 1777 ${target}/tmp
chown -c 0:0  ${target}/tmp

exit $error
