#!/bin/sh

# catnc is cat but without comment lines

# the Beowulf cluster; all nodes except the master node use classes from file class/atoms
case $HOSTNAME in
    atom00) echo "BEOWULF BEOWULF_MASTER NETTOOLS NTP DHCP_SERVER DNS_SERVER";;
    atom??) catnc atoms ;;
esac
