#! /bin/sh

# echo architecture in upper case
uname -s | tr /a-z/ /A-Z/
[ -x "`which dpkg`" ] && dpkg --print-installation-architecture | tr /a-z/ /A-Z/

# all hosts named ant?? are using the classes in file anthill
case $HOSTNAME in
    ant??) cat anthill ;;
esac

# all hosts named nuerburg? are becoming web kiosk systems
case $HOSTNAME in
    nuerburg?) cat wwwkiosk ;;
esac

# the Beowulf cluster; all nodes except the master node use classes from file class/atoms
case $HOSTNAME in
    atom00) echo BEOWULF_MASTER ;;
    atom??) cat atoms ;;
esac

# if host belongs to class C subnet 134.95.9.0 use class NET_9
# exclude all hosts with an IP address above 200
case $IPADDR in
    134.95.9.2??) ;;
    134.95.*.*)	cat koeln ; echo "CS_KOELN NET_9" ;;
    134.95.9.*)	echo "CS_KOELN NET_9" ;;
esac

# our notebooks
case $HOSTNAME in
    paeffgen|schlaeffli)
	cat notebook
	echo "BOOTWINDOWS"
	;;
    pittermaennche)
	cat notebook
	echo "BOOTP_SERVER"
	;;
esac


# use a list of classes for a demo machine
case $HOSTNAME in
    demohost)
	cat demo
	;;
esac
