#! /bin/sh

# if host belongs to class C subnet 123.45.6.0 use class NET_6
# exclude all hosts with an IP address above 200
case $IPADDR in
    123.45.6.2??) ;;
    123.45.*.*)	catnc koeln ;;
    123.45.6.*)	echo "CS_KOELN NET_6" ;;
esac

