#! /bin/sh

# create a tarball of FAI nfsroot, for those how don't have Debain yet
# Thomas Lange, (c) copyright 2001

exclude="--exclude nfsroot/usr/share/doc --exclude nfsroot/usr/doc \
--exclude nfsroot/var/tmp/base* \
--exclude nfsroot/usr/man \
--exclude nfsroot/usr/share/man \
--exclude nfsroot/usr/share/info \
--exclude nfsroot/lib/modules \
--exclude nfsroot/boot/vmlinuz-* --exclude nfsroot/boot/System.map-*"

cd /usr/lib/fai/nfsroot || exit 0
cd ..
tar $exclude -Icvf /tmp/nfsroot.tar.bz2 nfsroot
