#! /bin/sh

# set link in /boot/fai to installimage for host $1


link() {

	echo $1 now booting installimage
    	rm -f /boot/fai/$1
	ln -s installimage /boot/fai/$1 
}


hosts="01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16"

if [ $1 = "all" ];then
    for i in $hosts
    do
	link roy$i
    done
    exit
else
    link $1
fi


