#! /bin/sh

# Thomas Lange, lange@informatik.uni-koeln.de, (c) 2001

# create partitial debian mirror using debmirror from Joey and rsync
# http://cvs.kitenet.net/joey-cvs/bin/debmirror

host=ftp.de.debian.org
destdir=/files/scratch/debian
arch=i386
debug="--debug"
debug=
defopt="$debug --getcontents --host=$host --nosource --dist=stable"

# even one should not mirror the security site, but I will do it.
debmirror /files/scratch/debian-security $debug --nosource -h security.debian.org -r debian-security -d stable/updates --arch=$arch,all --nocleanup

# proposed-updates will also get packages for other architectures
debmirror $destdir --arch=$arch $defopt --ignore="non-US/|disks-$arch/|security/" --adddir=dists/proposed-updates

debmirror $destdir/non-US $defopt -r /debian-non-US -s non-US/main,non-US/contrib,non-US/non-free

# now get the disks
rsync -av ftp.de.debian.org::debian/dists/stable/main/disks-$arch $destdir/dists/stable/main/
