#! /bin/bash

# (c) Thomas Lange, 2001-2011, lange@debian.org
# (c) Michael Goetze, 2010, mgoetze@mgoetze.net

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# set root password
$ROOTCMD usermod -p $ROOTPW root

exit $error

