#! /bin/sh

# check_status <command run> <its result status>

cmd=$1
st=$2

if [ $st == 0 ]; then
   res="OK."
else
   res="FAILED with exit code $st."
fi
# put result in the log file
echo "$cmd: $res" | tee -a $LOGDIR/status.log
