#! /bin/sh

# $Id$

# create a writeable area on the install client

mount -n -t proc proc /proc
# start devfsd if needed
if [ -c /dev/.devfsd ]; then
    /sbin/devfsd /dev
fi

# if we have shm use it as ramdisk
mount -t tmpfs tmpfs /tmp || {
    ramdevice=/dev/ram0
    mke2fs -q -m 0 $ramdevice && echo "ramdisk $ramdevice created"
    mount -n $ramdevice /tmp
}
mount --bind /tmp /dev/shm
# now create the required subdirectories
mkdir -p /tmp/etc /tmp/target /dev/shm/network /tmp/var/lib/discover
mkrw /var/run /var/log
cd /tmp/var && mkdir tmp lock spool

