#! /bin/sh

# create a resolv.conf using the DHCP or BOOTP information
if [ "$DNSSRVS" ]; then
	[ "$DOMAIN" ] && echo "domain $DOMAIN" >/tmp/etc/resolv.conf
	for dnshost in $DNSSRVS ; do
	    echo "nameserver $dnshost" >>/tmp/etc/resolv.conf
	done
else
    # use the resolv.conf from the installserver
    cp -p /etc/resolv.conf-installserver /tmp/etc/resolv.conf
fi
