#!/bin/sh

# Short-Description: Reboot FAI in a clean manner

echo FAI: installation aborted.
echo "Hit <ENTER> to obtain a shell"
echo reboot with: faireboot
openvt -c1 -f -w -- /bin/bash
cd /
umount -ar
reboot -dfi
