#! /bin/bash

if ! command -v set_bootstick >&/dev/null; then
    if [ -f /usr/lib/fai/subroutines ]; then
        . /usr/lib/fai/subroutines
    else
        echo "Cannot find /usr/lib/fai/subroutines"
        echo "Please install package fai-client"
    fi
fi

set_bootstick
all_disks_and_size | checkdisk $FAI_BOOTSTICK | once_only
