#!/bin/sh

### BEGIN INIT INFO
# Provides:          fai-abort
# Required-Start:    $remote_fs
# Required-Stop:
# Default-Start:     2
# Default-Stop:
### END INIT INFO

case "$1" in
    start) ;;
    stop) ;;
    restart) ;;
    force-reload) ;;
esac

echo FAI: installation aborted.
echo reboot with: faireboot
echo or after a logout
sh
cd /
umount -ar
reboot -dfi
