#!/bin/sh

case "$1" in
    start) ;;
    stop) ;;
    restart) ;;
    force-reload) ;;
esac

echo FAI: installation aborted.
echo reboot with: faireboot
echo or after a logout
sh
cd /
umount -ar
reboot -dfi
