#!/bin/bash

### BEGIN SUBROUTINE INFO
# Provides-Var:
# Requires-Var:    $FAI_CONFIG_SRC
# Suggests-Var:
# Short-Description: get $FAI by local path
### END SUBROUTINE INFO

localpath=$(expr match "$FAI_CONFIG_SRC" '.*://\(/.*\)')
echo "Using local path $localpath"
