#!/bin/bash

# (c) 2002-2006 Henning Glawe <glaweh@debian.org>

### BEGIN SUBROUTINE INFO
# Provides-Var:
# Requires-Var:    $FAI_CONFIG_SRC $FAI $LOGDIR
# Suggests-Var:
# Short-Description: get $FAI from an svn repository.
### END SUBROUTINE INFO

# matched string: "svn://user@host/svnpath"
# strings without user@ are processed below
protocol=$(expr match "$FAI_CONFIG_SRC" '\([^:]*\)://')
username=$(expr match "$FAI_CONFIG_SRC" '[^:]*://\([^@]*\)@')
svnpath=$(expr match "$FAI_CONFIG_SRC" '[^:]*://[^@]\+@\([^[:space:]]\+\)')
[ -n "$username" ] && user="--username $username"
[ -z "$username" ] && svnurl=$FAI_CONFIG_SRC # if no user is specified

case $protocol in
	svn)
		svnurl="svn://$svnpath"
		;;
        svn+ssh)
	        svnurl="svn+ssh://$svnpath"
		user=""
		export SVN_SSH="ssh -l $username"
		;;
	svn+file)
		svnurl="file://$svnpath"
		;;
	svn+http)
		svnurl="http://$svnpath"
		;;
	svn+https)
		svnurl="https://$svnpath"
		;;
	*)
		echo "get-config-dir-svn: protocol $protocol not implemented"
		exit 1
		;;
esac
		

if [ -d "$FAI/.svn" ] ; then
   echo "Updating SVN in $FAI"
   cd $FAI
   svn up $user | grep -v 'Updated to revision' > $LOGDIR/getconf.log
else 
   echo "Checking out SVN"
   svn co $user $svnurl $FAI | grep -v 'Checked out revision' > $LOGDIR/getconf.log
fi
