#!/bin/bash
### BEGIN SUBROUTINE INFO
# Provides-Var:
# Requires-Var:    $FAI_CONFIG_SRC $FAI
# Suggests-Var:
# Short-Description: get $FAI by mounting it via nfs
### END SUBROUTINE INFO

SERVER=$(expr match "$FAI_CONFIG_SRC" '.*://\([^/]*\)/.*')
NFSPATH=$(expr match "$FAI_CONFIG_SRC" '.*://[^/]*\(/.*\)')

mount $romountopt $SERVER:$NFSPATH $FAI &&
echo "Configuration space $FAI mounted from $FAI_LOCATION"
