#! /bin/sh

# $Id: load_keymap_consolechars 3861 2006-09-05 13:41:49Z lange $

[ "$CONSOLEFONT" ] &&
	consolechars -v -f /usr/share/consolefonts/$CONSOLEFONT.psf.gz

# nothing to do if $KEYMAP is undefined
[ "$KEYMAP" ] || exit

echo -n "Loading keymap(s) $KEYMAP ..."
loadkeys -q $KEYMAP && echo "done."
