#! /bin/sh

# $Id$

[ "$CONSOLEFONT" ] &&
	consolechars -v -f /usr/share/consolefonts/$CONSOLEFONT.psf.gz

# nothing to do if FAI_KEYMAP is undefined
[ "$KEYMAP" ] || exit

echo -n "Loading keymap(s) $KEYMAP ..."
loadkeys -q $KEYMAP && echo "done."
