#! /bin/bash

#*********************************************************************
#
# mkramdisk -- mount a ramdisk on top of a directory
#
# This script is part of FAI (Fully Automatic Installation)
# (c) 2003-2010 by Thomas Lange, lange@informatik.uni-koeln.de
# Universitaet zu Koeln
#
#*********************************************************************

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
mount_ramdisk() {

    # save all dirs and files under directory $1
    # mount tmpfs on top of dir $1
    # extract dirs and files into tmpfs

    local n=

    if [ ! -d "$1" ]; then
	echo "WARNING: $1 is not a directory. Cannot make it writeable."
	return
    fi

    echo

    set -e
    local tmp1=$(mktemp) || exit 12
    tar -C $1 -cf $tmp1 .
    mount $2 $3 -t tmpfs tmpfs $1 || exit 13
    echo "Ramdisk mounted onto $1"
    tar -C $1 -xf $tmp1
    rm -f $tmp1
    set +e
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
umount_ramdisk() {

    # put contents of ramdisk back to original location on harddisk

    disk=$1
    ram=${disk}-in-ramdisk

    # test, if a ramdisk is mounted to this directory 
    mount | grep -q " $1 type tmpfs"
    if [ $? -eq 1 ]; then
	echo "$d is not a mounted ramdisk."
	return
    fi

    set -e
    mkdir $ram
    mount --move $disk $ram   # move current ramdisk to a new location
    rm -rf $disk
    cp -a  $ram $disk   # copy ramdisk contents to disk
    umount $ram
    echo "Ramdisk on $d umounted"
    rmdir  $ram
    set +e
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

size= # no default size
umount=0

while getopts ns:u opt ; do
    case "$opt" in
        u) umount=1 ;;
        s) size="-o size=$OPTARG" ;;
        n) mtab="-n" ;;
        esac
done
shift $(($OPTIND - 1))

# do not use the ramdisk if FAI_NORAMDISK is set to 1
[ X$FAI_NORAMDISK = X1 ] && return

for d in "$@"; do
    if [ $umount -eq 1 ]; then
	umount_ramdisk $d
    else
	[ -d "$d" ] && mount_ramdisk $d $size $mtab
    fi
done
