#! /bin/bash

#*********************************************************************
#
# This script is part of FAI (Fully Automatic Installation)
# (c) 2003-2006 by Thomas Lange, lange@informatik.uni-koeln.de
# Universitaet zu Koeln
#
#*********************************************************************

# variables needed: FAI_VERSION, do_init_tasks

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
_prcopyleft() {

    cat <<-EOF
             -------------------------------------------------
                   Fully Automatic Installation  -  FAI

               $FAI_VERSION  Copyright (c) 1999-2006
               Thomas Lange  <lange@informatik.uni-koeln.de>
             -------------------------------------------------
EOF
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# color logo only if initial install
color_logo=$do_init_tasks

# set red color, but not on some archs
[ -e /.nocolorlogo ] && color_logo=0
[ -n "$console" ] && color_logo=0  # no red logo if console was defined on the command line
case $HOSTTYPE in
    sparc*|powerpc*) color_logo=0 ;;
esac

[ $color_logo -eq 1 ] && echo -ne "\ec\e[1;31m"

_prcopyleft | tee -a $LOGDIR/fai.log

if [ $color_logo -eq 1 ]; then
	echo -ne "\e[7;0r"
	echo -ne "\e[9B\e[1;m"
fi
