#! /bin/bash

# This script is part of FAI (Fully Automatic Installation)
# (c) 2023-2024 by Thomas Lange, lange@debian.org

# start fai directly or inside screen or tmux

. /usr/lib/fai/subroutines
eval_cmdline
define_fai_flags

if [ X$flag_screen = X1 ]; then
    screen -S FAI /usr/sbin/fai
    exec /etc/init.d/fai-abort
elif [ X$flag_tmux = X1 ]; then
    tmux new-session -s FAI /usr/sbin/fai
    exec /etc/init.d/fai-abort
else
    exec /usr/sbin/fai
fi
