#! /bin/bash

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

# set root password
if [ -n "$ROOTPW" ]; then
    $ROOTCMD usermod -p "$ROOTPW" root
else
    $ROOTCMD usermod -L root
fi

exit $error

