#! /bin/bash

# (c) Thomas Lange, 2001-2008, lange@debian.org
# (c) Michael Goetze, 2010, mgoetze@mgoetze.net

error=0 ; trap "error=$((error|1))" ERR

# set root password
$ROOTCMD usermod -p $ROOTPW root

exit $error

