#!/bin/bash
#
# Capabilities get lost when creating the fai base.tar.xz image.
# Restore them here.
#

set -e

if [ ! -x $target/sbin/setcap ] ; then
    exit 0
fi

for FILE in /bin/ping /bin/ping6 /usr/bin/fping /usr/bin/fping6; do
    if [ -x $target/$FILE -a ! -h $target/$FILE ] ; then
        if $ROOTCMD /sbin/setcap cap_net_raw+ep $FILE; then
            echo "Setcap worked! $FILE is not suid!"
        fi
    fi
done
if [ -x $target/usr/bin/systemd-detect-virt ] ; then
    $ROOTCMD /sbin/setcap cap_dac_override,cap_sys_ptrace+ep /usr/bin/systemd-detect-virt
fi
