#! /bin/bash

error=0 ; trap "error=$((error|1))" ERR

ainsl -av ${target}/etc/mailname ${HOSTNAME}
sed -i -e "s/^UTC.*/UTC=${UTC}/" $target/etc/default/rcS
sed -i -e 's#/sbin/getty 38400#/sbin/getty -f /etc/issue.linuxlogo 38400#' ${target}/etc/inittab

exit $error
