#! /bin/bash

set -e
. /usr/share/debconf/confmodule

# check if installserver value is already set, otherwise set default 
db_get fai/installserver
if [ "$RET" = "" ]; then
    db_set fai/installserver $(hostname)
fi    

db_input medium fai/installserver || true
db_go || true

# mirrorhost is by default the installserver
db_get fai/installserver
INSTALLSERVER=$RET

db_get fai/mirrorhost
if [ "$RET" = "" ]; then
    db_set fai/mirrorhost ftp.debian.org
fi    
db_input medium fai/mirrorhost || true

db_input medium fai/run-faisetup-on-install || true

db_go || true
