#! /bin/sh

set -e

case "$1" in
    purge)
        . /etc/fai/fai.conf
	if [ -z "$FAI_CONFIGDIR" ]; then
	    echo "\$FAI_CONFIGDIR is not defined. Can't remove it."
	else
	    rm -rf $FAI_CONFIGDIR
	fi
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear) ;;

    *)
        echo "postrm called with unknown argument \`$1'" >&2
        exit 1

esac

#DEBHELPER#

exit 0
