#! /bin/bash

# setup script that is only run once at boot time

echo "Creating the nfsroot for FAI."

. /etc/fai/fai.conf

if [ ! -d "$FAI_CONFIGDIR/class" ]; then
    mkdir -p $FAI_CONFIGDIR
    cp -a /usr/share/doc/fai-doc/examples/simple/* $FAI_CONFIGDIR
fi

fai-setup 2>&1 | tee /var/log/fai-setup.log

echo "Log files are saved to /var/log/fai-setup.log"

# remove me
rm $0
