#! /bin/sh

# dump keytable
echo dump keyboard table
dumpkeys | gzip -9f >$target/etc/console-tools/default.kmap.gz

# if $kernelimage if not a debfile, then it's the kernel version

# create dummy link, so package kernel-image-* makes new correcxt link
ln -s /boot/vmlinuz-nolink $target/vmlinuz

if [ -f $files/packages/$kernelimage ]; then
   /usr/bin/yes 'n' | /usr/bin/dpkg --root=$target -i $files/packages/$kernelimage
else
   # default kernel
   yes 'n' | chroot $target apt-get install kernel-image-$kernelimage
fi
