#! /bin/sh

# copyright Thomas Lange 2001, lange@debian.org

# this is the function: AppendIfNoSuchLine
egrep -q "^auto" $target/etc/modules 2>/dev/null || echo "auto" >> $target/etc/modules

# a list of modules which are loaded at boot time
for module in $moduleslist; do
    echo $module >> $target/etc/modules
done

ifclass LILO && {
    # write lilo.conf and install lilo to disk
    echo "Creating lilo.conf for /vmlinuz"
    cat > $target/etc/lilo.conf <<-EOF
	boot=$BOOT_DEVICE
	root=$ROOT_PARTITION
	install=/boot/boot.b
	map=/boot/map
	vga=normal
	delay=50

	image=/vmlinuz
	label=linux
        read-only

	image=/vmlinuz.old
	label=linux.old
	read-only
	optional
	$liloappend
EOF

    $target/sbin/lilo -r $target
}

ifclass GRUB && {

    kernelname=/vmlinuz
    echo "Installing grub and boot entry for $kernelname"
    grub-install --root-directory=$target $BOOT_DEVICE
    broot=`device2grub $ROOT_PARTITION`

    cat > $target/boot/grub/menu.lst <<-EOF

	# created by FAI
	
	timeout 10
	default 0
	color cyan/blue white/blue

	title Debian GNU/Linux, $kernelname $kernelimage
	root $broot
	kernel $kernelname
EOF

    rdev $target/$kernelname $ROOT_PARTITION
    echo "Grub installed for $kernelimage $broot"
}
