#! /bin/sh

# copyright Thomas Lange 2001, lange@debian.org

# this is the function: AppendIfNoSuchLine
egrep -q "^auto" $target/etc/modules 2>/dev/null || echo "auto" >> $target/etc/modules

# a list of modules, that are loaded at boot time
echo $moduleslist >> $target/etc/modules


ifclass LILO && {
    # write lilo.conf and install lilo to disk
    cat > $target/etc/lilo.conf <<-EOF
	boot=$BOOT_DEVICE
	root=$ROOT_PARTITION
	install=/boot/boot.b
	map=/boot/map
	vga=normal
	delay=50
	#
	image=/vmlinuz
	label=linux
	$liloappend
EOF

    $target/sbin/lilo -r $target
}

ifclass GRUB && {
    echo "GRUB not yet supported"
}
