#! /bin/sh

# dump keytable
echo dump keyboard table
dumpkeys | gzip -9f >$target/etc/console-tools/default.kmap.gz

if [ -n "$hdparm" ]; then

    cat > $FAI_ROOT/etc/init.d/hdparm <<-EOF
    #! /bin/sh
    # added by FAI
    # tune my harddisks
    $hdparm
EOF
    chmod a+rx $FAI_ROOT/etc/init.d/hdparm
    ln -s ../init.d/hdparm $FAI_ROOT/etc/rcS.d/S61hdparm
fi

# if $kernelimage if not a debfile, then it's the kernel version

# create dummy link, so package kernel-image-* makes new correcxt link
ln -s /boot/vmlinuz-nolink $target/vmlinuz

if [ -f $files/packages/$kernelimage ]; then
   yes 'n' | dpkg --root=$target -i $files/packages/$kernelimage
else
   # default kernel package
   yes 'n' | chroot $target apt-get install $kernelimage
fi
