#! /bin/sh

ln -sf /usr/local/vol ${target}/vol

# since this file is only executed if class FAICLIENT is defined,
# following definition if a logical AND of both classes
#
# create this tar-file on your debian-binserver with:
# tar -cf FAICLIENT -C /etc/alternatives .
ifclass DATALESS && tar -C $target/etc/alternatives -xvpf $files/etc/alternatives/FAICLIENT

