#! /bin/sh

# copyright Thomas Lange 2001, lange@debian.org
# remove backup files from cfeninge (*.cfedited)

dirs="root etc var"

for path in $dirs; do
    find $FAI_ROOT/$path -maxdepth 25 -name \*.cfedited -o -name \*.cfsaved | xargs rm
done

# the system is now configured
rm -f $FAI_ROOT/sbin/unconfigured.sh
