#! /bin/sh

# some notebook specific changes
# Thomas Lange 2000-2003; lange@debian.org

# tune max-mount-counts for ext2 on notebooks
maxcount=131
partitions=`mount|grep $target |grep "type ext2"|perl -ane 'print "$F[0] "'`
for part in $partitions; do
    tune2fs -c $maxcount $part
done

# make cdrom readable for all
chmod 444 $target/dev/hdc
