#! /bin/sh

# create resolv.conf
# Thomas Lange 2000

for class in $classes; do
    resolv=$FAI_FILES/etc/resolv.conf/$class
    [ -f $resolv ] && cp -p $resolv $FAI_ROOT/etc/resolv.conf
done

[ -s /tmp/etc/resolv.conf ] && cp -p /tmp/etc/resolv.conf $FAI_ROOT/etc
