#! /bin/sh

catnc() {
    # cat but no comment lines
    egrep -v "^#" $1
}

# echo architecture and OS name in upper case. Do NOT remove these two lines
uname -s | tr '[:lower:]' '[:upper:]'
[ -x "`which dpkg`" ] && dpkg --print-installation-architecture | tr /a-z/ /A-Z/

# the Beowulf cluster; all nodes except the master node use classes from file class/atoms
case $HOSTNAME in
    atom00) echo "BEOWULF BEOWULF_MASTER NETTOOLS NTP DHCP_SERVER DNS_SERVER";;
    atom??) catnc atoms ;;
esac

# use a list of classes for our demo machine
case $HOSTNAME in
    demohost)
	catnc demo ;;
esac
