#! /bin/sh

# echo architecture and OS name in upper case. Do NOT remove these two lines
uname -s | tr '[:lower:]' '[:upper:]'
[ -x "`which dpkg`" ] && dpkg --print-installation-architecture | tr a-z A-Z

[ -f /boot/RUNNING_FROM_FAICD ] && echo "FAICD"
exit 0