#! /bin/sh

# echo architecture and OS name in upper case. Do NOT remove these two lines
uname -s | tr '[:lower:]' '[:upper:]'
[ -x "`which dpkg`" ] && dpkg --print-installation-architecture | tr /a-z/ /A-Z/

[ -f /boot/RUNNING_FROM_FAICD ] && echo "FAICD"

# use a list of classes for our demo machine
case $HOSTNAME in
    demohost)
	echo "FAIBASE GRUB DHCPC DEMO" ;;
    gnomehost)
	echo "FAIBASE GRUB DHCPC DEMO XFREE GNOME";;
    *)
	echo "FAIBASE GRUB DHCPC" ;;
esac
