#! /bin/bash

# assign classes to hosts

# use a list of classes for our demo machine
case $HOSTNAME in
    faiserver)
	echo "FAIBASE DEBIAN DEMO FAISERVER" ;;
    demohost|client*)
	echo "FAIBASE DEBIAN DHCPC DEMO" ;;
    gnomehost)
	echo "FAIBASE DEBIAN DHCPC DEMO XORG GNOME";;
    atom*)
	echo "FAIBASE DEBIAN DHCPC DEMO" ;;
    bear)
	echo "FAIBASE DEBIAN DHCPC LVM_XEN_SERVER XEN" ;;
    puma)
	echo "FAIBASE DEBIAN DHCPC RAID_XEN_VIRTUAL" ;;
    centos)
	echo "FAIBASE CENTOS"
	ifclass I386 && echo CENTOS5_32
	ifclass AMD64 && echo CENTOS5_64
	exit 0 ;; # CentOS does not use the GRUB class
    *)
	echo "FAIBASE DEBIAN DHCPC" ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB 
exit 0
