#! /bin/sh

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in
    demohost)
	echo "FAIBASE DHCPC DEMO" ;;
    gnomehost)
	echo "FAIBASE DHCPC DEMO XFREE GNOME";;
    *)
	echo "FAIBASE DHCPC" ;;
esac

ifclass I386 && echo "GRUB"
