#! /bin/sh

# determine the list of all hosts that respond to a ping
#
# (c) Thomas Lange, Institut fuer Informatik, Uni Koeln, 1998-2001

# example for a Beowulf cluster
server=atom00
nodeprefix=atom
endnum=25


make_hostlist() {

    # create the list of all hosts
    i=1
    while [ $i -le $endnum ]; do
	num=`printf "%.2d" $i`
	nodes="$nodes $nodeprefix$num"
	i=$(($i+1))
    done
    allhosts="$server $nodes"
}

usage() {
cat <<EOF
   Usage: all_hosts [parameter]

    all_hosts without any option show all answering hosts.

    -h     print this message.
    -n     show all non answering hosts.
    -p     print only the list of all hosts

EOF
exit 0
}

gethosts() {
    for h in $allhosts
    do
	if ping -c 1 $h >/dev/null;
	then hosts=$hosts"$h ";
	else nohosts=$nohosts"$h ";
	fi
    done
}

make_hostlist
while getopts anhp opt
do
        case "$opt" in
	n) gethosts && echo $nohosts && exit ;;
        h) usage ;;
        p) echo $allhosts ;;
	*) usage
	    exit 2;;
	esac
done
[ -n "$1" ] || gethosts && echo $hosts
