#! /bin/sh

# create a tarball of FAI (inlcuding nfsroot, tftp and the configuration), for
# those how don't have Debain yet
# What's missing: bootptab or dhcp.conf
#
# Thomas Lange, (c) copyright 2001-2003

# How to use this tarball:
# After unpacking copy base2_2.tgz to $nfsroot/var/tmp, set up bootpd

tarball=/tmp/fai-tarball.tar.bz2
nfsroot=/usr/lib/fai/nfsroot

cd /
tar -cvf - $nfsroot /boot/fai /usr/local/share/fai | bzip2 > $tarball
echo $tarball created.
