#! /bin/sh

# (c) 2001, Thomas Lange
#
# set link for tftpboot in /boot/fai to an image for a host
# or for all hosts with prefix and a number

# examples:
# tlink installimage bigfoot
# tlink installimage ant06
# tlink installimage all ant
# tlink nodeimage all ant
#
# tlink             shows all file in /boot/fai
# tlink ant01       shows syslink for ant01

# define the range for client numbers using prefix
startnum=1
endnum=25

image=$1
host=$2
prefix=$3

tftpdir=/boot/fai
# - - - - - - - - - - - - - - - - - - - -
link() {

    	rm -f $ $tftpdir/$1
	ln -s $image $tftpdir/$1 && echo $1 now booting $image
}
# - - - - - - - - - - - - - - - - - - - -
showlink() {

    # show current link for host

    ls -l $tftpdir/$1
    exit 0
}
# - - - - - - - - - - - - - - - - - - - -

# create list of hosts without prefix
i=$startnum
while [ $i -le $endnum ]; do
    num=`printf "%.2d" $i`
    hostnums="$hostnums $num"
    i=$(($i+1))
done

# show one or all files
[ X"$host" = X ] && showlink $1

if [ $host = "all" ];then
    for i in $hostnums
    do
	link $prefix$i
    done
    exit
else
    link $host
fi
