#! /bin/sh

# $Id$
# reboot FAI correctly, Thomas Lange, Uni Koeln, copyright 2000-2003

. /etc/fai/fai.conf

while getopts s opt ; do
        case "$opt" in
        s) fai-savelog -r ;;
        esac
done
FAI_ROOT=/tmp/target
ROOTCMD="chroot $FAI_ROOT"
export ROOTCMD

cd /
killall -STOP rcS
killall -q apt-get dpkg tar gzip yes cat syslogd 

[ "X" == "X$SSH_CLIENT" -a  "$TERM" != "dumb" ] && killall -q sshd

fai-divert -R

umount $FAI_ROOT/proc $FAI_ROOT/dev/pts
umount -ar

echo "$HOSTNAME now rebooting"

if [ "X" == "X$SSH_CLIENT" -a  "$TERM" != "dumb" ]; then
    exec reboot -dfi
else
    killall -CONT rcS
    killall rcS
    init 6 &
fi
