#!/bin/sh

# this script is not used. Now mknbi-linux and imggen is used to create a bootable
# kernel image for 3com network cards

echo "This script is not used in FAI. mknbi-linux is used instead."
ecit 0

# TODO: create a bootable floppy
# syslinux: root=ip-server:/usr/lib/fai/nfsroot
# -h => help

# $Id$
#*********************************************************************
#
# make-fai-tftpimage -- create tftp boot image for bootable network card
#
# This script is part of FAI (Fully Automatic Installation)
# Copyright (c) 2000 by Thomas Lange, lange@informatik.uni-koeln.de
# Universitaet zu Koeln
#
#*********************************************************************

# This scripts builds a bootable tftp boot image for network cards
# maybe you need a header (preloader)

# tested with the MBA v3.10 (or later) eproms 

usage() {
    cat <<EOF
make-fai-tftpimage bzImage tftpimage rootdevice [header] [kernel-par] ...

Parameter

    bzImage        input file, a kernel
    tftpimage      tftpimage that will be created
    header         is appended before the XXXX
    rootdevice     normally /dev/nfs
    kernel-par     parameter that are passed to the kernel
EOF
exit 0
}

[ $# -eq 0 ] && usage

. /etc/fai.conf

mnt=/tmp/mountpoint.$$
dosdisk=/tmp/dosdisk.$$

if [ "$UID" -ne 0 ]; then
 echo "You must be root!"
 exit 9
fi

# where to find emptydosdisk and headers
base=$LIBFAI/kernel/

bzimage=$1
shift
tftpimage=$1
shift
rootdevice=$1
shift
header=$1
shift
parameter=$*

if [ -f $tftpimage ]; then
    mv $tftpimage $tftpimage.old
    echo moved $tftpimage to $tftpimage.old
fi

trap 'cd /;umount $mnt ; rm -rf $dosdisk $bootdev $mnt' EXIT HUP INT QUIT

mkdir $mnt
gzip -dc $base/emptydosdisk.gz > $dosdisk
mount $dosdisk $mnt -t msdos -o loop
cp $bzimage $mnt/linux
cat <<EOF >$mnt/syslinux.cfg
TIMEOUT 20
PROMPT 0
DEFAULT linux
EOF

app="APPEND root=$rootdevice"
[ -n "$parameter" ] && app="$app $parameter" 
echo $app >> $mnt/syslinux.cfg

#[ -n "$parameter" ] && echo "APPEND \"$parameter\"" >> $mnt/syslinux.cfg
syslinux $dosdisk

if [ -n "$header" ]; then
    test [ -f $header ] && cat $header $dosdisk > $tftpimage
    test [ -f $base/$header ] && cat $base/$header $dosdisk > $tftpimage
else
    cp $dosdisk $tftpimage
fi

chmod a=r $tftpimage

exit 0
