#!/bin/sh

# TODO: create a bootable floppy
# syslinux: root=ip-server:/usr/lib/fai/nfsroot
# -h => help

# $Id$
#*********************************************************************
#
# mk3comimage -- create tftp boot image for 3Com network card
#
# This script is part of FAI (Fully Automatic Installation)
# Copyright (c) 2000 by Thomas Lange, lange@informatik.uni-koeln.de
# Universitaet zu Koeln
#
#*********************************************************************

# This scripts builds a bootable tftp boot image for 3Com network cards
# tested with the MBA v3.10 (or later) eproms 

usage() {
    cat <<EOF
mk3comimage [options] bzImage tftpimage rootdevice [parameter] ...

Parameter

    bzImage        input file, a kernel
    tftpimage      tftpimage that will be created
    rootdevice     normally /dev/nfs
EOF
exit 0
}

[ $# -eq 0 ] && usage

. /etc/fai.conf

mnt=/tmp/mountpoint.$$
dosdisk=/tmp/dosdisk.$$

if [ "$UID" -ne 0 ]; then
 echo "You must be root!"
 exit 9
fi

# where to find emptydosdisk and imagegen_firstblock
base=$LIBFAI/kernel/

bzimage=$1
shift
tftpimage=$1
shift
rootdevice=$1
shift
parameter=$*

if [ -f $tftpimage ]; then
    mv $tftpimage $tftpimage.old
    echo moved $tftpimage to $tftpimage.old
fi

trap 'cd /;umount $mnt ; rm -rf $dosdisk $bootdev $mnt' EXIT HUP INT QUIT

mkdir $mnt
gzip -dc $base/emptydosdisk.gz > $dosdisk
mount $dosdisk $mnt -t msdos -o loop
cp $bzimage $mnt/linux
cat <<EOF >$mnt/syslinux.cfg
TIMEOUT 20
PROMPT 0
DEFAULT linux
EOF

app="APPEND root=$rootdevice"
[ -n "$parameter" ] && app="$app $parameter" 
echo $app >> $mnt/syslinux.cfg

#[ -n "$parameter" ] && echo "APPEND \"$parameter\"" >> $mnt/syslinux.cfg
syslinux $dosdisk
cat $base/imagegen_firstblock $dosdisk > $tftpimage
chmod a=r $tftpimage

exit 0
