#! /bin/sh

# $Id$
#*********************************************************************
#
# mount2target -- mount local disk to $target using a fstab file
#
# This script is part of FAI (Fully Automatic Installation)
# (c) 2001 by Thomas Lange, lange@informatik.uni-koeln.de
# Universitaet zu Koeln
#
#*********************************************************************
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
# 
# A copy of the GNU General Public License is available as
# `/usr/share/common-licences/GPL' in the Debian GNU/Linux distribution
# or on the World Wide Web at http://www.gnu.org/copyleft/gpl.html.  You
# can also obtain it by writing to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#*********************************************************************

target=$1
fscklog=/tmp/fsck.log
fstab=/tmp/fstab
fscheck=1
mountoption=

# exit if no parameter given
[ "$target" ] || {
    echo No parameter. Specify target directory.
    exit 1
}

_mount2target() {

while read mountpoint device type ; do
      [ $verbose ] && echo "mounting $device to $target$mountpoint type: $type opt: $mountoption"
      mkdir -p $target/$mountpoint
      # should we fsck the partition first ?
      [ "fscheck" ] && fsck -nt $type $device >> $fscklog 2>&1
      mount $mountoption $device $target$mountpoint
done
}

# skip comment lines; do not now mount swap; sort lines, so parent
# directories are mounted first

egrep -v "^#|^none|[[:space:]]swap[[:space:]]|^$" $fstab | \
awk '{printf("%s %s %s\n"),$2,$1,$3}' | sort | _mount2target
