#!/bin/bash
# $Id$
#*********************************************************************
#
# rcS_fai -- main installation script executed after booting
#
# This script is part of FAI (Fully Automatic Installation)
# (c) 1999-2003 by Thomas Lange, lange@informatik.uni-koeln.de
# Universitaet zu Koeln
#
#*********************************************************************
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
# 
# A copy of the GNU General Public License is available as
# `/usr/share/common-licences/GPL' in the Debian GNU/Linux distribution
# or on the World Wide Web at http://www.gnu.org/copyleft/gpl.html. You
# can also obtain it by writing to the Free Software Foundation, Inc.,
# 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
#*********************************************************************

#set -xv # for full debugging

# some variables
FAI_VERSION=FAIVERSIONSTRING
stamp=/tmp/FAI_INSTALLATION_IN_PROGRESS
romountopt="-o noatime,nolock,ro"
fstab=fstab  # Solaris uses vfstab

# default classes before calling task defvar. Will be overwritten by task defvar
# the type of operating system (linux, sunos)
oclass=`uname -s | tr /a-z/ /A-Z/`
classes="DEFAULT $oclass $HOSTNAME LAST"
unset oclass

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
fai_init() {

    local sub osname
    set -a # now export all variables

    # read fai.conf
    # linux dir
    [ -f /etc/fai/fai.conf ] && . /etc/fai/fai.conf
    # solaris dir
    [ -f /tmp/install_config/fai/fai.conf ] && . /tmp/install_config/fai/fai.conf
    # some variables are not needed here
    unset KERNELPACKAGE NFSROOT NFSROOT_PACKAGES FAI_ROOTPW SSH_IDENTITY
    unset ftpserver debdist

    # read subroutine definitions
    sub=$FAI_SHAREDIR/subroutines
    [ -f $sub ] && . $sub
    [ -f $sub-$OS_TYPE ] && . $sub-$OS_TYPE
    unset FAI_SHAREDIR

    DEBIAN_FRONTEND=noninteractive
    # local disks are mounted to $FAI_ROOT
    [ -z "$FAI_ROOT" ] && FAI_ROOT=/tmp/target
    # executed command in the environment of the new system
    ROOTCMD="chroot $FAI_ROOT"
    # no chroot needed
    [ "$FAI_ROOT" = '/' ] && ROOTCMD=
    # directory where temporary log files are stored
    # set default value if nothing is set in fai.conf
    [ -z "$LOGDIR" ] && LOGDIR=/tmp/fai
    mkdir -p $LOGDIR

    # several log files
    diskvar=$LOGDIR/disk_var.sh
    moduleslog=$LOGDIR/modules.log
    rcslog=$LOGDIR/rcS.log
    # rcsfaivar saves variables which are sourced by remote logins during installation
    rcsfaivar=/tmp/rcsfai.var

    # variables for cfengine
    files=$FAI/files
    target=$FAI_ROOT

    umask 022
    trap 'echo "Now rebooting";faireboot' INT QUIT

    if [ X$OS_TYPE = Xlinux ]; then
	osname='Debian GNU/Linux'
	ifup lo
	[ -x /sbin/portmap ] && /sbin/portmap
	mount -t devpts devpts /dev/pts
	mount -o remount,noatime,ro,rsize=8192 /dev/root /
	cat /proc/kmsg >/dev/tty4 &
    fi
    if [ X$OS_TYPE = Xsunos ]; then
	osname='Sun Solaris'
    fi

    {
    cat <<-EOF

             -----------------------------------------------------
               Fully Automatic Installation for $osname
               $FAI_VERSION

               Copyright (c) 1999-2003 Thomas Lange
               <lange@informatik.uni-koeln.de>
             -----------------------------------------------------

EOF
    save_dmesg
    } > >( tee -a $rcslog )  2>&1
}
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Main routine
# callarg=$1

export PATH=/usr/local/sbin:/usr/local/bin:/usr/lib/fai:/bin:/sbin:/usr/bin:/usr/sbin:

# Solaris has already a writable /tmp directory
[ `uname -s` = Linux ] && create_ramdisk

fai_init
{
task confdir
task setup
task defclass
task defvar
} > >( tee -a $rcslog )  2>&1

# if you want to recall rcS_fai
# [ -n $callarg ] && FAI_ACTION=$callarg

(task action > >( tee -a $rcslog ) 2>&1)
