#! /bin/sh

# fake start-stop-daemon; a dummy program that never starts daemons

for opt in $* ; do
    case "$opt" in
        --oknodo) oknodo=1 ;;
        --start) start=1 ;;
        --stop) stop=1 ;;
        esac
done


[ -n "$start" -a -n "$oknodo" ] && exit 1
[ -n "$stop" -a -z "$oknodo" ] && exit 1

exit 0
