#!/bin/sh
# install adsm/tivoli software

ln $target/opt/tivoli/tsm/client/ba/bin/dsm $target/usr/local/sbin/dsm
ln $target/opt/tivoli/tsm/client/ba/bin/dsmc $target/usr/local/sbin/dsmc
# why not using ftar?
fcopy -r /etc/adsm /opt/tivoli
chmod 0600 $target/etc/adsm/*
