#! /bin/sh

# (c) Thomas Lange, 2001-2003, lange@debian.org

# if $kernelimage is not a debfile, then it's the kernel version
# create dummy link, so package kernel-image-* makes new correct link
ln -s /boot/vmlinuz-nolink $target/vmlinuz

# install additional packags that are located in /fai/files/packages/
if [ -f /fai/files/packages/Packages.gz ]; then
    # Mm. It seems to be a simple repository. I assume it's configured in sources.list
    [ "$addpackages" ] &&  yes '' | $ROOTCMD apt-get install $addpackages
else
    [ "$addpackages" ] && cd $FAI/files/packages && dpkg -i --root=$target $addpackages
fi

# xmcd loops when doing an automatic installation
ifclass AUDIO && {
    yes 'n' | $ROOTCMD apt-get install xmcd
    fcopy -r /etc/xmcd/
}

# Do not use $kernelimage when you specified it by $addpackages
if [ -f $files/packages/$kernelimage ]; then
   yes 'n' | dpkg --root=$target -i $files/packages/$kernelimage
else
   # default kernel package
   echo "do_symlinks = Yes" > $target/etc/kernel-img.conf
   yes 'n' | $ROOTCMD apt-get install $kernelimage
fi

echo $HOSTNAME     > $target/etc/hostname
echo $time_zone    > $target/etc/timezone
ln -fs /usr/share/zoneinfo/${time_zone} $target/etc/localtime

fcopy /etc/hosts /etc/motd

# make /root accessable only by root
chmod 0700 $target/root
chown root:root $target/root
# copy default dotfiles for root account
fcopy -r /root

# create keyboard layput table
dumpkeys | gzip -9f >$target/etc/console/boottime.kmap.gz

# create NIS/NONIS config
fcopy /etc/nsswitch.conf /etc/host.conf
ifclass NONIS && rm -f $target/etc/defaultdomain
if ifclass NIS; then
    echo $YPDOMAIN > $target/etc/defaultdomain
    rm -f $target/etc/yp.conf
    for s in $YPSRVR; do
	echo "ypserver $s" >> $target/etc/yp.conf
    done
fi

ifclass USR_LOCAL_COPY && {
    # you have to mount /usr/local
    # mount -o ro $bserver:/usr/local /usr/local
    cp -a /usr/local $target/usr
}

ifclass USR_LOCAL_RSYNC && {
    echo "Syncing /usr/local via $LOGUSER@$bserver"
    vopt=
    [ "$verbose" ] && vopt=-v
    rsync $vopt --delete -a $LOGUSER@$bserver:/usr/local/ $target/usr/local/
}

# make floppy read and writeable for all users
chmod a+rw $target/dev/fd*
# cdrom's are read only for all
chmod a+r $target/dev/sr* 

fcopy /etc/X11/XF86Config-4

# put CD-ROM into fstab and exports
# if cdromdevice is defined in *.var, use that value
# if you have both a SCSI and an IDE CD-ROM -> Uuuuups, this will fail
[ "$cdromdevice" ] || cdromdevice=`grep -H cdrom /proc/ide/hd*/media | head -1 | awk -F/ '{print $4}'`
[ "$cdromdevice" ] || cdromdevice=`grep -q CD-ROM /proc/scsi/scsi && echo "sr0"`
if [ "$cdromdevice" ]; then
    echo "/dev/$cdromdevice  /cdrom   auto    ro,user,nohide,noauto 0 0" >>$target/etc/fstab
    echo "/cdrom        *(ro)" >> $target/etc/exports
fi
# if a second cd-rom exists we assume that this is the cd-writer
if [ `grep "Type:.*CD-ROM" /proc/scsi/scsi | wc -l` -gt 1 ]; then
    echo "/dev/sr1  /cdrec  auto    ro,user,nohide,noauto 0 0" >>$target/etc/fstab
    echo "/cdrec        *(ro)" >> $target/etc/exports
    mkdir $target/cdrec
fi

# copy bootsector programm to local disk
[ -d /usr/local/sbin ] && cp -p /usr/sbin/bootsector $target/usr/local/sbin

# copy ldp.conf if printing is done via Network and NIS
ifclass NISLPRCLIENT && {
    $ROOTCMD update-rc.d -f lprng remove
    fcopy /usr/local/share/LPRng/pcfilter
    rm -f $target/etc/cron.daily/lprng
}

# install local cron jobs
ftar /etc/cron.d

# copy for all NET_9 Linux-Clients exim.conf
ifclass LINUX && fcopy /etc/exim/exim.conf /etc/aliases

# only used for acroread5
ifclass USR_LOCAL_MOUNT || ftar /usr/local

# change cdrecord default
fcopy -i /etc/default/cdrecord
# set cdrecord to suid 
[ -f $target/usr/bin/cdrecord ] && chmod u+s $target/usr/bin/cdrecord
chmod a+rw $target/dev/scd0 $target/dev/scd1

# install mozilla plugins
ifclass LINUX && ifclass CS_KOELN && ftar /usr/lib/mozilla

# enable access to /dev/sg3 for everybody if a scsi scanner exists
# this makes sure, that xsane is able to find the connected scsi scanners
# only for kueppers
# /dev/sg3 is accessed if scanner is added by scsi-add at runtime
ifclass kueppers && chmod a+rw $target/dev/sg3

# for our local installation we copy a backuped ssh_key
if [ -d $target/files/scratch/${HOSTNAME}-backup/etc/ssh ]; then
    cp -p $target/files/scratch/${HOSTNAME}-backup/etc/ssh/ssh_host* $target/etc/ssh
fi

ifclass DATALESS && ftar /etc/alternatives

# if TeX/LaTeX is installed build german hyphenation
if $ROOTCMD dpkg -l |grep -q tetex-bin ; then
    echo "Creating german hyphenation for TeX/LaTeX"
    cat > $target/tmp/mkgermantex.sh <<EOF
cd /tmp
echo "\input hyphen.cfg" > hyphen.tex
initex /usr/share/texmf/tex/plain/config/tex.ini
cp /var/lib/texmf/web2c/tex.fmt /var/lib/texmf/web2c/tex.fmt.old
cp tex.fmt /var/lib/texmf/web2c
initex /usr/share/texmf/tex/latex/base/latex.ltx
cp latex.fmt /var/lib/texmf/web2c
EOF
    chmod u+x $target/tmp/mkgermantex.sh
    $ROOTCMD /tmp/mkgermantex.sh
fi
