#! /bin/sh

# class WWWKIOSK sets the Netscape into KIOSK mode.  
# WWWKIOSK 
if ifclass WWWKIOSK; then 
    fcopy /root/.shutdown.sh /etc/network/interfaces /etc/hosts /etc/X11/app-defaults/Netscape 
    chown root:root $target/root/.shutdown.sh
    chmod 0755 $target/root/.shutdown.sh
    ln -fs /usr/lib/netscape/477/communicator/communicator-smotif.real $target/usr/local/bin/netscape
    ftar /home
    ${ROOTCMD} chown -R opac:opac /home/opac
fi