#! /bin/bash
# support for GRUB version 2 (1.98-1)

error=0 ; trap "error=$((error|1))" ERR

set -a

# during softupdate use this file
[ -r $LOGDIR/disk_var.sh ] && . $LOGDIR/disk_var.sh

[ -z "$BOOT_DEVICE" ]    && exit 701

$ROOTCMD grub-mkdevicemap --no-floppy

for device in $BOOT_DEVICE; do
  GROOT=$($ROOTCMD grub-probe -tdrive -d $device)
  $ROOTCMD grub-install --no-floppy --modules="lvm raid" "$GROOT"
  echo "Grub installed on $device = $GROOT"
done

$ROOTCMD update-grub

exit $error
