#! /bin/bash
# support for GRUB version 2

error=0; trap 'error=$(($?>$error?$?:$error))' ERR # save maximum error code

set -a
# during softupdate use this file
[ -r $LOGDIR/disk_var.sh ] && . $LOGDIR/disk_var.sh

[ -z "$BOOT_DEVICE" ]    && exit 701

$ROOTCMD update-grub

# skip the rest, if not an initial installation
if [ $FAI_ACTION != "install" ]; then
    exit $error
fi

# check if mdadm has been forgotten
if grep -q active /proc/mdstat 2>/dev/null; then
    if [ ! -d $target/etc/mdadm ]; then
	echo WARNING: Found Software RAID, but mdadm was not installed
    fi
fi

$ROOTCMD grub-mkdevicemap --no-floppy
GROOT=$($ROOTCMD grub-probe -tdrive -d $BOOT_DEVICE)

# Check if RAID is used for the boot device
if [[ $BOOT_DEVICE =~ '/dev/md' ]]; then
    raiddev=${BOOT_DEVICE#/dev/}
    # install grub on all members of RAID
    for device in `LC_ALL=C perl -ne 'if(/^'$raiddev'\s.+raid\d+\s(.+)/){ $_=$1; s/\d+\[\d+\]//g; print }' /proc/mdstat`; do
	echo Install grub on /dev/$device
	$ROOTCMD grub-install --no-floppy "/dev/$device"
    done
else
    $ROOTCMD grub-install --no-floppy "$GROOT"
    if [ $? -eq 0 ]; then
        echo "Grub installed on $BOOT_DEVICE = $GROOT"
    fi
fi

exit $error
