#! /bin/bash

# assign classes hosts

# use a list of classes for our demo machine
case $HOSTNAME in
    faiserver)
	echo "FAIBASE DEMO FAISERVER" ;;
    demohost)
	echo "FAIBASE DHCPC DEMO" ;;
    gnomehost)
	echo "FAIBASE DHCPC DEMO XORG GNOME";;
    atom*)
	echo "FAIBASE DHCPC DEMO" ;;
    bear)
	echo "FAIBASE DHCPC LVM_XEN_SERVER XEN" ;;
    puma)
	echo "FAIBASE DHCPC RAID_XEN_VIRTUAL" ;;
    *)
	echo "FAIBASE DHCPC" ;;
esac

(ifclass I386 || ifclass AMD64) && echo GRUB_PC
exit 0
