#! /bin/sh

# catnc is cat but without comment lines

# echo architecture and OS name in upper case. Do NOT remove these two lines
uname -s | tr '[:lower:]' '[:upper:]'
[ -x "`which dpkg`" ] && dpkg --print-installation-architecture | tr /a-z/ /A-Z/

# use a list of classes for our demo machine
case $HOSTNAME in
    demohost)
	catnc demo ;;
esac
