#! /bin/sh

catnc() {
    # cat but no comment lines
    grep -v "^#" $1
}


# echo architecture and OS name in upper case. Do NOT remove these two lines
uname -s | tr /a-z/ /A-Z/
[ -x "`which dpkg`" ] && dpkg --print-installation-architecture | tr /a-z/ /A-Z/

# all hosts named ant?? are using the classes in file anthill
case $HOSTNAME in
    ant??) catnc anthill ;;
esac

# all hosts named nuerburg? are becoming web kiosk systems
case $HOSTNAME in
    nuerburg?) catnc wwwkiosk ;;
esac

# the Beowulf cluster; all nodes except the master node use classes from file class/atoms
case $HOSTNAME in
    atom00) echo BEOWULF_MASTER ;;
    atom??) catnc atoms ;;
esac

# if host belongs to class C subnet 134.95.9.0 use class NET_9
# exclude all hosts with an IP address above 200
case $IPADDR in
    134.95.9.2??) ;;
    134.95.*.*)	catnc koeln ; echo "CS_KOELN NET_9" ;;
    134.95.9.*)	echo "CS_KOELN NET_9" ;;
esac

# our notebooks
case $HOSTNAME in
    paeffgen|schlaeffli)
	catnc notebook
	echo "BOOTWINDOWS"
	;;
    pittermaennche)
	catnc notebook
	echo "BOOTP_SERVER"
	;;
esac

# use a list of classes for a demo machine
case $HOSTNAME in
    demohost)
	catnc demo
	;;
esac
